/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CcmsSalaryMonthly implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        employeeCode;
    private String        salaryMonth;
    private String        plantCode;
    private Integer       salaryYear;
    private Double        workedDays;
    private Double        offDays;
    private Double        paidDays;
    private Double        nhFhWorking;
    private Double        offWorking;
    private Double        otHrs;
    private Double        offHrs;
    private Double        basic;
    private Double        hra;
    private Double        allowance;
    private Double        gross1;
    private Double        attBonus;
    private Double        otWages;
    private Double        offWages;
    private Double        motiAllowance;
    private Double        coldRoomAllowance;
    private Double        etpAllowance;
    private Double        gross2;
    private Double        pf;
    private Double        erPf;
    private Double        esi;
    private Double        erEsi;
    private Double        lwfEe;
    private Double        totalDeduction;
    private Double        netPay;
    private Double        serviceCharge;
    private Double        lwfEr;
    private Double        total;
    private Double        cgst;
    private Double        sgst;
    private Double        gross3;
    private String        billApproved;
    private String        status;
    private String        createdBy;
    private LocalDateTime createdOn;
    private String        lastChangedBy;
    private LocalDateTime lastChangedOn;

    public CcmsSalaryMonthly() {}

    public CcmsSalaryMonthly(CcmsSalaryMonthly value) {
        this.employeeCode = value.employeeCode;
        this.salaryMonth = value.salaryMonth;
        this.plantCode = value.plantCode;
        this.salaryYear = value.salaryYear;
        this.workedDays = value.workedDays;
        this.offDays = value.offDays;
        this.paidDays = value.paidDays;
        this.nhFhWorking = value.nhFhWorking;
        this.offWorking = value.offWorking;
        this.otHrs = value.otHrs;
        this.offHrs = value.offHrs;
        this.basic = value.basic;
        this.hra = value.hra;
        this.allowance = value.allowance;
        this.gross1 = value.gross1;
        this.attBonus = value.attBonus;
        this.otWages = value.otWages;
        this.offWages = value.offWages;
        this.motiAllowance = value.motiAllowance;
        this.coldRoomAllowance = value.coldRoomAllowance;
        this.etpAllowance = value.etpAllowance;
        this.gross2 = value.gross2;
        this.pf = value.pf;
        this.erPf = value.erPf;
        this.esi = value.esi;
        this.erEsi = value.erEsi;
        this.lwfEe = value.lwfEe;
        this.totalDeduction = value.totalDeduction;
        this.netPay = value.netPay;
        this.serviceCharge = value.serviceCharge;
        this.lwfEr = value.lwfEr;
        this.total = value.total;
        this.cgst = value.cgst;
        this.sgst = value.sgst;
        this.gross3 = value.gross3;
        this.billApproved = value.billApproved;
        this.status = value.status;
        this.createdBy = value.createdBy;
        this.createdOn = value.createdOn;
        this.lastChangedBy = value.lastChangedBy;
        this.lastChangedOn = value.lastChangedOn;
    }

    public CcmsSalaryMonthly(
        String        employeeCode,
        String        salaryMonth,
        String        plantCode,
        Integer       salaryYear,
        Double        workedDays,
        Double        offDays,
        Double        paidDays,
        Double        nhFhWorking,
        Double        offWorking,
        Double        otHrs,
        Double        offHrs,
        Double        basic,
        Double        hra,
        Double        allowance,
        Double        gross1,
        Double        attBonus,
        Double        otWages,
        Double        offWages,
        Double        motiAllowance,
        Double        coldRoomAllowance,
        Double        etpAllowance,
        Double        gross2,
        Double        pf,
        Double        erPf,
        Double        esi,
        Double        erEsi,
        Double        lwfEe,
        Double        totalDeduction,
        Double        netPay,
        Double        serviceCharge,
        Double        lwfEr,
        Double        total,
        Double        cgst,
        Double        sgst,
        Double        gross3,
        String        billApproved,
        String        status,
        String        createdBy,
        LocalDateTime createdOn,
        String        lastChangedBy,
        LocalDateTime lastChangedOn
    ) {
        this.employeeCode = employeeCode;
        this.salaryMonth = salaryMonth;
        this.plantCode = plantCode;
        this.salaryYear = salaryYear;
        this.workedDays = workedDays;
        this.offDays = offDays;
        this.paidDays = paidDays;
        this.nhFhWorking = nhFhWorking;
        this.offWorking = offWorking;
        this.otHrs = otHrs;
        this.offHrs = offHrs;
        this.basic = basic;
        this.hra = hra;
        this.allowance = allowance;
        this.gross1 = gross1;
        this.attBonus = attBonus;
        this.otWages = otWages;
        this.offWages = offWages;
        this.motiAllowance = motiAllowance;
        this.coldRoomAllowance = coldRoomAllowance;
        this.etpAllowance = etpAllowance;
        this.gross2 = gross2;
        this.pf = pf;
        this.erPf = erPf;
        this.esi = esi;
        this.erEsi = erEsi;
        this.lwfEe = lwfEe;
        this.totalDeduction = totalDeduction;
        this.netPay = netPay;
        this.serviceCharge = serviceCharge;
        this.lwfEr = lwfEr;
        this.total = total;
        this.cgst = cgst;
        this.sgst = sgst;
        this.gross3 = gross3;
        this.billApproved = billApproved;
        this.status = status;
        this.createdBy = createdBy;
        this.createdOn = createdOn;
        this.lastChangedBy = lastChangedBy;
        this.lastChangedOn = lastChangedOn;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.employee_code</code>.
     */
    public String getEmployeeCode() {
        return this.employeeCode;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.employee_code</code>.
     */
    public CcmsSalaryMonthly setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.salary_month</code>.
     */
    public String getSalaryMonth() {
        return this.salaryMonth;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.salary_month</code>.
     */
    public CcmsSalaryMonthly setSalaryMonth(String salaryMonth) {
        this.salaryMonth = salaryMonth;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.plant_code</code>.
     */
    public String getPlantCode() {
        return this.plantCode;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.plant_code</code>.
     */
    public CcmsSalaryMonthly setPlantCode(String plantCode) {
        this.plantCode = plantCode;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.salary_year</code>.
     */
    public Integer getSalaryYear() {
        return this.salaryYear;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.salary_year</code>.
     */
    public CcmsSalaryMonthly setSalaryYear(Integer salaryYear) {
        this.salaryYear = salaryYear;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.worked_days</code>.
     */
    public Double getWorkedDays() {
        return this.workedDays;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.worked_days</code>.
     */
    public CcmsSalaryMonthly setWorkedDays(Double workedDays) {
        this.workedDays = workedDays;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.off_days</code>.
     */
    public Double getOffDays() {
        return this.offDays;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.off_days</code>.
     */
    public CcmsSalaryMonthly setOffDays(Double offDays) {
        this.offDays = offDays;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.paid_days</code>.
     */
    public Double getPaidDays() {
        return this.paidDays;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.paid_days</code>.
     */
    public CcmsSalaryMonthly setPaidDays(Double paidDays) {
        this.paidDays = paidDays;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.nh_fh_working</code>.
     */
    public Double getNhFhWorking() {
        return this.nhFhWorking;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.nh_fh_working</code>.
     */
    public CcmsSalaryMonthly setNhFhWorking(Double nhFhWorking) {
        this.nhFhWorking = nhFhWorking;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.off_working</code>.
     */
    public Double getOffWorking() {
        return this.offWorking;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.off_working</code>.
     */
    public CcmsSalaryMonthly setOffWorking(Double offWorking) {
        this.offWorking = offWorking;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.ot_hrs</code>.
     */
    public Double getOtHrs() {
        return this.otHrs;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.ot_hrs</code>.
     */
    public CcmsSalaryMonthly setOtHrs(Double otHrs) {
        this.otHrs = otHrs;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.off_hrs</code>.
     */
    public Double getOffHrs() {
        return this.offHrs;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.off_hrs</code>.
     */
    public CcmsSalaryMonthly setOffHrs(Double offHrs) {
        this.offHrs = offHrs;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.basic</code>.
     */
    public Double getBasic() {
        return this.basic;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.basic</code>.
     */
    public CcmsSalaryMonthly setBasic(Double basic) {
        this.basic = basic;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.hra</code>.
     */
    public Double getHra() {
        return this.hra;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.hra</code>.
     */
    public CcmsSalaryMonthly setHra(Double hra) {
        this.hra = hra;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.allowance</code>.
     */
    public Double getAllowance() {
        return this.allowance;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.allowance</code>.
     */
    public CcmsSalaryMonthly setAllowance(Double allowance) {
        this.allowance = allowance;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.gross1</code>.
     */
    public Double getGross1() {
        return this.gross1;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.gross1</code>.
     */
    public CcmsSalaryMonthly setGross1(Double gross1) {
        this.gross1 = gross1;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.att_bonus</code>.
     */
    public Double getAttBonus() {
        return this.attBonus;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.att_bonus</code>.
     */
    public CcmsSalaryMonthly setAttBonus(Double attBonus) {
        this.attBonus = attBonus;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.ot_wages</code>.
     */
    public Double getOtWages() {
        return this.otWages;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.ot_wages</code>.
     */
    public CcmsSalaryMonthly setOtWages(Double otWages) {
        this.otWages = otWages;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.off_wages</code>.
     */
    public Double getOffWages() {
        return this.offWages;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.off_wages</code>.
     */
    public CcmsSalaryMonthly setOffWages(Double offWages) {
        this.offWages = offWages;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.moti_allowance</code>.
     */
    public Double getMotiAllowance() {
        return this.motiAllowance;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.moti_allowance</code>.
     */
    public CcmsSalaryMonthly setMotiAllowance(Double motiAllowance) {
        this.motiAllowance = motiAllowance;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.cold_room_allowance</code>.
     */
    public Double getColdRoomAllowance() {
        return this.coldRoomAllowance;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.cold_room_allowance</code>.
     */
    public CcmsSalaryMonthly setColdRoomAllowance(Double coldRoomAllowance) {
        this.coldRoomAllowance = coldRoomAllowance;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.etp_allowance</code>.
     */
    public Double getEtpAllowance() {
        return this.etpAllowance;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.etp_allowance</code>.
     */
    public CcmsSalaryMonthly setEtpAllowance(Double etpAllowance) {
        this.etpAllowance = etpAllowance;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.gross2</code>.
     */
    public Double getGross2() {
        return this.gross2;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.gross2</code>.
     */
    public CcmsSalaryMonthly setGross2(Double gross2) {
        this.gross2 = gross2;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.pf</code>.
     */
    public Double getPf() {
        return this.pf;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.pf</code>.
     */
    public CcmsSalaryMonthly setPf(Double pf) {
        this.pf = pf;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.er_pf</code>.
     */
    public Double getErPf() {
        return this.erPf;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.er_pf</code>.
     */
    public CcmsSalaryMonthly setErPf(Double erPf) {
        this.erPf = erPf;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.esi</code>.
     */
    public Double getEsi() {
        return this.esi;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.esi</code>.
     */
    public CcmsSalaryMonthly setEsi(Double esi) {
        this.esi = esi;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.er_esi</code>.
     */
    public Double getErEsi() {
        return this.erEsi;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.er_esi</code>.
     */
    public CcmsSalaryMonthly setErEsi(Double erEsi) {
        this.erEsi = erEsi;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.lwf_ee</code>.
     */
    public Double getLwfEe() {
        return this.lwfEe;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.lwf_ee</code>.
     */
    public CcmsSalaryMonthly setLwfEe(Double lwfEe) {
        this.lwfEe = lwfEe;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.total_deduction</code>.
     */
    public Double getTotalDeduction() {
        return this.totalDeduction;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.total_deduction</code>.
     */
    public CcmsSalaryMonthly setTotalDeduction(Double totalDeduction) {
        this.totalDeduction = totalDeduction;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.net_pay</code>.
     */
    public Double getNetPay() {
        return this.netPay;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.net_pay</code>.
     */
    public CcmsSalaryMonthly setNetPay(Double netPay) {
        this.netPay = netPay;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.service_charge</code>.
     */
    public Double getServiceCharge() {
        return this.serviceCharge;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.service_charge</code>.
     */
    public CcmsSalaryMonthly setServiceCharge(Double serviceCharge) {
        this.serviceCharge = serviceCharge;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.lwf_er</code>.
     */
    public Double getLwfEr() {
        return this.lwfEr;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.lwf_er</code>.
     */
    public CcmsSalaryMonthly setLwfEr(Double lwfEr) {
        this.lwfEr = lwfEr;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.total</code>.
     */
    public Double getTotal() {
        return this.total;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.total</code>.
     */
    public CcmsSalaryMonthly setTotal(Double total) {
        this.total = total;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.cgst</code>.
     */
    public Double getCgst() {
        return this.cgst;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.cgst</code>.
     */
    public CcmsSalaryMonthly setCgst(Double cgst) {
        this.cgst = cgst;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.sgst</code>.
     */
    public Double getSgst() {
        return this.sgst;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.sgst</code>.
     */
    public CcmsSalaryMonthly setSgst(Double sgst) {
        this.sgst = sgst;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.gross3</code>.
     */
    public Double getGross3() {
        return this.gross3;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.gross3</code>.
     */
    public CcmsSalaryMonthly setGross3(Double gross3) {
        this.gross3 = gross3;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.bill_approved</code>.
     */
    public String getBillApproved() {
        return this.billApproved;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.bill_approved</code>.
     */
    public CcmsSalaryMonthly setBillApproved(String billApproved) {
        this.billApproved = billApproved;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.status</code>.
     */
    public CcmsSalaryMonthly setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.created_by</code>.
     */
    public CcmsSalaryMonthly setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.created_on</code>.
     */
    public CcmsSalaryMonthly setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.last_changed_by</code>.
     */
    public String getLastChangedBy() {
        return this.lastChangedBy;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.last_changed_by</code>.
     */
    public CcmsSalaryMonthly setLastChangedBy(String lastChangedBy) {
        this.lastChangedBy = lastChangedBy;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_salary_monthly.last_changed_on</code>.
     */
    public LocalDateTime getLastChangedOn() {
        return this.lastChangedOn;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_salary_monthly.last_changed_on</code>.
     */
    public CcmsSalaryMonthly setLastChangedOn(LocalDateTime lastChangedOn) {
        this.lastChangedOn = lastChangedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CcmsSalaryMonthly other = (CcmsSalaryMonthly) obj;
        if (employeeCode == null) {
            if (other.employeeCode != null)
                return false;
        }
        else if (!employeeCode.equals(other.employeeCode))
            return false;
        if (salaryMonth == null) {
            if (other.salaryMonth != null)
                return false;
        }
        else if (!salaryMonth.equals(other.salaryMonth))
            return false;
        if (plantCode == null) {
            if (other.plantCode != null)
                return false;
        }
        else if (!plantCode.equals(other.plantCode))
            return false;
        if (salaryYear == null) {
            if (other.salaryYear != null)
                return false;
        }
        else if (!salaryYear.equals(other.salaryYear))
            return false;
        if (workedDays == null) {
            if (other.workedDays != null)
                return false;
        }
        else if (!workedDays.equals(other.workedDays))
            return false;
        if (offDays == null) {
            if (other.offDays != null)
                return false;
        }
        else if (!offDays.equals(other.offDays))
            return false;
        if (paidDays == null) {
            if (other.paidDays != null)
                return false;
        }
        else if (!paidDays.equals(other.paidDays))
            return false;
        if (nhFhWorking == null) {
            if (other.nhFhWorking != null)
                return false;
        }
        else if (!nhFhWorking.equals(other.nhFhWorking))
            return false;
        if (offWorking == null) {
            if (other.offWorking != null)
                return false;
        }
        else if (!offWorking.equals(other.offWorking))
            return false;
        if (otHrs == null) {
            if (other.otHrs != null)
                return false;
        }
        else if (!otHrs.equals(other.otHrs))
            return false;
        if (offHrs == null) {
            if (other.offHrs != null)
                return false;
        }
        else if (!offHrs.equals(other.offHrs))
            return false;
        if (basic == null) {
            if (other.basic != null)
                return false;
        }
        else if (!basic.equals(other.basic))
            return false;
        if (hra == null) {
            if (other.hra != null)
                return false;
        }
        else if (!hra.equals(other.hra))
            return false;
        if (allowance == null) {
            if (other.allowance != null)
                return false;
        }
        else if (!allowance.equals(other.allowance))
            return false;
        if (gross1 == null) {
            if (other.gross1 != null)
                return false;
        }
        else if (!gross1.equals(other.gross1))
            return false;
        if (attBonus == null) {
            if (other.attBonus != null)
                return false;
        }
        else if (!attBonus.equals(other.attBonus))
            return false;
        if (otWages == null) {
            if (other.otWages != null)
                return false;
        }
        else if (!otWages.equals(other.otWages))
            return false;
        if (offWages == null) {
            if (other.offWages != null)
                return false;
        }
        else if (!offWages.equals(other.offWages))
            return false;
        if (motiAllowance == null) {
            if (other.motiAllowance != null)
                return false;
        }
        else if (!motiAllowance.equals(other.motiAllowance))
            return false;
        if (coldRoomAllowance == null) {
            if (other.coldRoomAllowance != null)
                return false;
        }
        else if (!coldRoomAllowance.equals(other.coldRoomAllowance))
            return false;
        if (etpAllowance == null) {
            if (other.etpAllowance != null)
                return false;
        }
        else if (!etpAllowance.equals(other.etpAllowance))
            return false;
        if (gross2 == null) {
            if (other.gross2 != null)
                return false;
        }
        else if (!gross2.equals(other.gross2))
            return false;
        if (pf == null) {
            if (other.pf != null)
                return false;
        }
        else if (!pf.equals(other.pf))
            return false;
        if (erPf == null) {
            if (other.erPf != null)
                return false;
        }
        else if (!erPf.equals(other.erPf))
            return false;
        if (esi == null) {
            if (other.esi != null)
                return false;
        }
        else if (!esi.equals(other.esi))
            return false;
        if (erEsi == null) {
            if (other.erEsi != null)
                return false;
        }
        else if (!erEsi.equals(other.erEsi))
            return false;
        if (lwfEe == null) {
            if (other.lwfEe != null)
                return false;
        }
        else if (!lwfEe.equals(other.lwfEe))
            return false;
        if (totalDeduction == null) {
            if (other.totalDeduction != null)
                return false;
        }
        else if (!totalDeduction.equals(other.totalDeduction))
            return false;
        if (netPay == null) {
            if (other.netPay != null)
                return false;
        }
        else if (!netPay.equals(other.netPay))
            return false;
        if (serviceCharge == null) {
            if (other.serviceCharge != null)
                return false;
        }
        else if (!serviceCharge.equals(other.serviceCharge))
            return false;
        if (lwfEr == null) {
            if (other.lwfEr != null)
                return false;
        }
        else if (!lwfEr.equals(other.lwfEr))
            return false;
        if (total == null) {
            if (other.total != null)
                return false;
        }
        else if (!total.equals(other.total))
            return false;
        if (cgst == null) {
            if (other.cgst != null)
                return false;
        }
        else if (!cgst.equals(other.cgst))
            return false;
        if (sgst == null) {
            if (other.sgst != null)
                return false;
        }
        else if (!sgst.equals(other.sgst))
            return false;
        if (gross3 == null) {
            if (other.gross3 != null)
                return false;
        }
        else if (!gross3.equals(other.gross3))
            return false;
        if (billApproved == null) {
            if (other.billApproved != null)
                return false;
        }
        else if (!billApproved.equals(other.billApproved))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!createdBy.equals(other.createdBy))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (lastChangedBy == null) {
            if (other.lastChangedBy != null)
                return false;
        }
        else if (!lastChangedBy.equals(other.lastChangedBy))
            return false;
        if (lastChangedOn == null) {
            if (other.lastChangedOn != null)
                return false;
        }
        else if (!lastChangedOn.equals(other.lastChangedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.employeeCode == null) ? 0 : this.employeeCode.hashCode());
        result = prime * result + ((this.salaryMonth == null) ? 0 : this.salaryMonth.hashCode());
        result = prime * result + ((this.plantCode == null) ? 0 : this.plantCode.hashCode());
        result = prime * result + ((this.salaryYear == null) ? 0 : this.salaryYear.hashCode());
        result = prime * result + ((this.workedDays == null) ? 0 : this.workedDays.hashCode());
        result = prime * result + ((this.offDays == null) ? 0 : this.offDays.hashCode());
        result = prime * result + ((this.paidDays == null) ? 0 : this.paidDays.hashCode());
        result = prime * result + ((this.nhFhWorking == null) ? 0 : this.nhFhWorking.hashCode());
        result = prime * result + ((this.offWorking == null) ? 0 : this.offWorking.hashCode());
        result = prime * result + ((this.otHrs == null) ? 0 : this.otHrs.hashCode());
        result = prime * result + ((this.offHrs == null) ? 0 : this.offHrs.hashCode());
        result = prime * result + ((this.basic == null) ? 0 : this.basic.hashCode());
        result = prime * result + ((this.hra == null) ? 0 : this.hra.hashCode());
        result = prime * result + ((this.allowance == null) ? 0 : this.allowance.hashCode());
        result = prime * result + ((this.gross1 == null) ? 0 : this.gross1.hashCode());
        result = prime * result + ((this.attBonus == null) ? 0 : this.attBonus.hashCode());
        result = prime * result + ((this.otWages == null) ? 0 : this.otWages.hashCode());
        result = prime * result + ((this.offWages == null) ? 0 : this.offWages.hashCode());
        result = prime * result + ((this.motiAllowance == null) ? 0 : this.motiAllowance.hashCode());
        result = prime * result + ((this.coldRoomAllowance == null) ? 0 : this.coldRoomAllowance.hashCode());
        result = prime * result + ((this.etpAllowance == null) ? 0 : this.etpAllowance.hashCode());
        result = prime * result + ((this.gross2 == null) ? 0 : this.gross2.hashCode());
        result = prime * result + ((this.pf == null) ? 0 : this.pf.hashCode());
        result = prime * result + ((this.erPf == null) ? 0 : this.erPf.hashCode());
        result = prime * result + ((this.esi == null) ? 0 : this.esi.hashCode());
        result = prime * result + ((this.erEsi == null) ? 0 : this.erEsi.hashCode());
        result = prime * result + ((this.lwfEe == null) ? 0 : this.lwfEe.hashCode());
        result = prime * result + ((this.totalDeduction == null) ? 0 : this.totalDeduction.hashCode());
        result = prime * result + ((this.netPay == null) ? 0 : this.netPay.hashCode());
        result = prime * result + ((this.serviceCharge == null) ? 0 : this.serviceCharge.hashCode());
        result = prime * result + ((this.lwfEr == null) ? 0 : this.lwfEr.hashCode());
        result = prime * result + ((this.total == null) ? 0 : this.total.hashCode());
        result = prime * result + ((this.cgst == null) ? 0 : this.cgst.hashCode());
        result = prime * result + ((this.sgst == null) ? 0 : this.sgst.hashCode());
        result = prime * result + ((this.gross3 == null) ? 0 : this.gross3.hashCode());
        result = prime * result + ((this.billApproved == null) ? 0 : this.billApproved.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.lastChangedBy == null) ? 0 : this.lastChangedBy.hashCode());
        result = prime * result + ((this.lastChangedOn == null) ? 0 : this.lastChangedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CcmsSalaryMonthly (");

        sb.append(employeeCode);
        sb.append(", ").append(salaryMonth);
        sb.append(", ").append(plantCode);
        sb.append(", ").append(salaryYear);
        sb.append(", ").append(workedDays);
        sb.append(", ").append(offDays);
        sb.append(", ").append(paidDays);
        sb.append(", ").append(nhFhWorking);
        sb.append(", ").append(offWorking);
        sb.append(", ").append(otHrs);
        sb.append(", ").append(offHrs);
        sb.append(", ").append(basic);
        sb.append(", ").append(hra);
        sb.append(", ").append(allowance);
        sb.append(", ").append(gross1);
        sb.append(", ").append(attBonus);
        sb.append(", ").append(otWages);
        sb.append(", ").append(offWages);
        sb.append(", ").append(motiAllowance);
        sb.append(", ").append(coldRoomAllowance);
        sb.append(", ").append(etpAllowance);
        sb.append(", ").append(gross2);
        sb.append(", ").append(pf);
        sb.append(", ").append(erPf);
        sb.append(", ").append(esi);
        sb.append(", ").append(erEsi);
        sb.append(", ").append(lwfEe);
        sb.append(", ").append(totalDeduction);
        sb.append(", ").append(netPay);
        sb.append(", ").append(serviceCharge);
        sb.append(", ").append(lwfEr);
        sb.append(", ").append(total);
        sb.append(", ").append(cgst);
        sb.append(", ").append(sgst);
        sb.append(", ").append(gross3);
        sb.append(", ").append(billApproved);
        sb.append(", ").append(status);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(lastChangedBy);
        sb.append(", ").append(lastChangedOn);

        sb.append(")");
        return sb.toString();
    }
}
