/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CcmsEsiExcludedPlant implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        plantCode;
    private String        status;
    private LocalDateTime createdOn;
    private String        createdBy;
    private LocalDateTime lastModifiedOn;
    private String        lastModifiedBy;

    public CcmsEsiExcludedPlant() {}

    public CcmsEsiExcludedPlant(CcmsEsiExcludedPlant value) {
        this.plantCode = value.plantCode;
        this.status = value.status;
        this.createdOn = value.createdOn;
        this.createdBy = value.createdBy;
        this.lastModifiedOn = value.lastModifiedOn;
        this.lastModifiedBy = value.lastModifiedBy;
    }

    public CcmsEsiExcludedPlant(
        String        plantCode,
        String        status,
        LocalDateTime createdOn,
        String        createdBy,
        LocalDateTime lastModifiedOn,
        String        lastModifiedBy
    ) {
        this.plantCode = plantCode;
        this.status = status;
        this.createdOn = createdOn;
        this.createdBy = createdBy;
        this.lastModifiedOn = lastModifiedOn;
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_esi_excluded_plant.plant_code</code>.
     */
    public String getPlantCode() {
        return this.plantCode;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_esi_excluded_plant.plant_code</code>.
     */
    public CcmsEsiExcludedPlant setPlantCode(String plantCode) {
        this.plantCode = plantCode;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_esi_excluded_plant.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_esi_excluded_plant.status</code>.
     */
    public CcmsEsiExcludedPlant setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_esi_excluded_plant.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_esi_excluded_plant.created_on</code>.
     */
    public CcmsEsiExcludedPlant setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_esi_excluded_plant.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_esi_excluded_plant.created_by</code>.
     */
    public CcmsEsiExcludedPlant setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_esi_excluded_plant.last_modified_on</code>.
     */
    public LocalDateTime getLastModifiedOn() {
        return this.lastModifiedOn;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_esi_excluded_plant.last_modified_on</code>.
     */
    public CcmsEsiExcludedPlant setLastModifiedOn(LocalDateTime lastModifiedOn) {
        this.lastModifiedOn = lastModifiedOn;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_esi_excluded_plant.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_esi_excluded_plant.last_modified_by</code>.
     */
    public CcmsEsiExcludedPlant setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CcmsEsiExcludedPlant other = (CcmsEsiExcludedPlant) obj;
        if (plantCode == null) {
            if (other.plantCode != null)
                return false;
        }
        else if (!plantCode.equals(other.plantCode))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!createdBy.equals(other.createdBy))
            return false;
        if (lastModifiedOn == null) {
            if (other.lastModifiedOn != null)
                return false;
        }
        else if (!lastModifiedOn.equals(other.lastModifiedOn))
            return false;
        if (lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.plantCode == null) ? 0 : this.plantCode.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.lastModifiedOn == null) ? 0 : this.lastModifiedOn.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CcmsEsiExcludedPlant (");

        sb.append(plantCode);
        sb.append(", ").append(status);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(lastModifiedOn);
        sb.append(", ").append(lastModifiedBy);

        sb.append(")");
        return sb.toString();
    }
}
