/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CcmsGuestDetailsNew implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        empCode;
    private String        mealDate;
    private String        mealShift;
    private String        plantCode;
    private String        empType;
    private String        empName;
    private String        companyName;
    private String        department;
    private String        pointOfContact;
    private Integer       mealCount;
    private Integer       extraCount;
    private Integer       totalCount;
    private String        active;
    private String        createdBy;
    private LocalDateTime createdOn;
    private String        lastModifiedBy;
    private LocalDateTime lastModifiedOn;

    public CcmsGuestDetailsNew() {}

    public CcmsGuestDetailsNew(CcmsGuestDetailsNew value) {
        this.empCode = value.empCode;
        this.mealDate = value.mealDate;
        this.mealShift = value.mealShift;
        this.plantCode = value.plantCode;
        this.empType = value.empType;
        this.empName = value.empName;
        this.companyName = value.companyName;
        this.department = value.department;
        this.pointOfContact = value.pointOfContact;
        this.mealCount = value.mealCount;
        this.extraCount = value.extraCount;
        this.totalCount = value.totalCount;
        this.active = value.active;
        this.createdBy = value.createdBy;
        this.createdOn = value.createdOn;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedOn = value.lastModifiedOn;
    }

    public CcmsGuestDetailsNew(
        String        empCode,
        String        mealDate,
        String        mealShift,
        String        plantCode,
        String        empType,
        String        empName,
        String        companyName,
        String        department,
        String        pointOfContact,
        Integer       mealCount,
        Integer       extraCount,
        Integer       totalCount,
        String        active,
        String        createdBy,
        LocalDateTime createdOn,
        String        lastModifiedBy,
        LocalDateTime lastModifiedOn
    ) {
        this.empCode = empCode;
        this.mealDate = mealDate;
        this.mealShift = mealShift;
        this.plantCode = plantCode;
        this.empType = empType;
        this.empName = empName;
        this.companyName = companyName;
        this.department = department;
        this.pointOfContact = pointOfContact;
        this.mealCount = mealCount;
        this.extraCount = extraCount;
        this.totalCount = totalCount;
        this.active = active;
        this.createdBy = createdBy;
        this.createdOn = createdOn;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedOn = lastModifiedOn;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.emp_code</code>.
     */
    public String getEmpCode() {
        return this.empCode;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.emp_code</code>.
     */
    public CcmsGuestDetailsNew setEmpCode(String empCode) {
        this.empCode = empCode;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.meal_date</code>.
     */
    public String getMealDate() {
        return this.mealDate;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.meal_date</code>.
     */
    public CcmsGuestDetailsNew setMealDate(String mealDate) {
        this.mealDate = mealDate;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.meal_shift</code>.
     */
    public String getMealShift() {
        return this.mealShift;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.meal_shift</code>.
     */
    public CcmsGuestDetailsNew setMealShift(String mealShift) {
        this.mealShift = mealShift;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.plant_code</code>.
     */
    public String getPlantCode() {
        return this.plantCode;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.plant_code</code>.
     */
    public CcmsGuestDetailsNew setPlantCode(String plantCode) {
        this.plantCode = plantCode;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.emp_type</code>.
     */
    public String getEmpType() {
        return this.empType;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.emp_type</code>.
     */
    public CcmsGuestDetailsNew setEmpType(String empType) {
        this.empType = empType;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.emp_name</code>.
     */
    public String getEmpName() {
        return this.empName;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.emp_name</code>.
     */
    public CcmsGuestDetailsNew setEmpName(String empName) {
        this.empName = empName;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.company_name</code>.
     */
    public String getCompanyName() {
        return this.companyName;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.company_name</code>.
     */
    public CcmsGuestDetailsNew setCompanyName(String companyName) {
        this.companyName = companyName;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.department</code>.
     */
    public String getDepartment() {
        return this.department;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.department</code>.
     */
    public CcmsGuestDetailsNew setDepartment(String department) {
        this.department = department;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.point_of_contact</code>.
     */
    public String getPointOfContact() {
        return this.pointOfContact;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.point_of_contact</code>.
     */
    public CcmsGuestDetailsNew setPointOfContact(String pointOfContact) {
        this.pointOfContact = pointOfContact;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.meal_count</code>.
     */
    public Integer getMealCount() {
        return this.mealCount;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.meal_count</code>.
     */
    public CcmsGuestDetailsNew setMealCount(Integer mealCount) {
        this.mealCount = mealCount;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.extra_count</code>.
     */
    public Integer getExtraCount() {
        return this.extraCount;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.extra_count</code>.
     */
    public CcmsGuestDetailsNew setExtraCount(Integer extraCount) {
        this.extraCount = extraCount;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.total_count</code>.
     */
    public Integer getTotalCount() {
        return this.totalCount;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.total_count</code>.
     */
    public CcmsGuestDetailsNew setTotalCount(Integer totalCount) {
        this.totalCount = totalCount;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.active</code>.
     */
    public String getActive() {
        return this.active;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.active</code>.
     */
    public CcmsGuestDetailsNew setActive(String active) {
        this.active = active;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.created_by</code>.
     */
    public CcmsGuestDetailsNew setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.created_on</code>.
     */
    public CcmsGuestDetailsNew setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.last_modified_by</code>.
     */
    public CcmsGuestDetailsNew setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_guest_details_new.last_modified_on</code>.
     */
    public LocalDateTime getLastModifiedOn() {
        return this.lastModifiedOn;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_guest_details_new.last_modified_on</code>.
     */
    public CcmsGuestDetailsNew setLastModifiedOn(LocalDateTime lastModifiedOn) {
        this.lastModifiedOn = lastModifiedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CcmsGuestDetailsNew other = (CcmsGuestDetailsNew) obj;
        if (empCode == null) {
            if (other.empCode != null)
                return false;
        }
        else if (!empCode.equals(other.empCode))
            return false;
        if (mealDate == null) {
            if (other.mealDate != null)
                return false;
        }
        else if (!mealDate.equals(other.mealDate))
            return false;
        if (mealShift == null) {
            if (other.mealShift != null)
                return false;
        }
        else if (!mealShift.equals(other.mealShift))
            return false;
        if (plantCode == null) {
            if (other.plantCode != null)
                return false;
        }
        else if (!plantCode.equals(other.plantCode))
            return false;
        if (empType == null) {
            if (other.empType != null)
                return false;
        }
        else if (!empType.equals(other.empType))
            return false;
        if (empName == null) {
            if (other.empName != null)
                return false;
        }
        else if (!empName.equals(other.empName))
            return false;
        if (companyName == null) {
            if (other.companyName != null)
                return false;
        }
        else if (!companyName.equals(other.companyName))
            return false;
        if (department == null) {
            if (other.department != null)
                return false;
        }
        else if (!department.equals(other.department))
            return false;
        if (pointOfContact == null) {
            if (other.pointOfContact != null)
                return false;
        }
        else if (!pointOfContact.equals(other.pointOfContact))
            return false;
        if (mealCount == null) {
            if (other.mealCount != null)
                return false;
        }
        else if (!mealCount.equals(other.mealCount))
            return false;
        if (extraCount == null) {
            if (other.extraCount != null)
                return false;
        }
        else if (!extraCount.equals(other.extraCount))
            return false;
        if (totalCount == null) {
            if (other.totalCount != null)
                return false;
        }
        else if (!totalCount.equals(other.totalCount))
            return false;
        if (active == null) {
            if (other.active != null)
                return false;
        }
        else if (!active.equals(other.active))
            return false;
        if (createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!createdBy.equals(other.createdBy))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (lastModifiedBy == null) {
            if (other.lastModifiedBy != null)
                return false;
        }
        else if (!lastModifiedBy.equals(other.lastModifiedBy))
            return false;
        if (lastModifiedOn == null) {
            if (other.lastModifiedOn != null)
                return false;
        }
        else if (!lastModifiedOn.equals(other.lastModifiedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.empCode == null) ? 0 : this.empCode.hashCode());
        result = prime * result + ((this.mealDate == null) ? 0 : this.mealDate.hashCode());
        result = prime * result + ((this.mealShift == null) ? 0 : this.mealShift.hashCode());
        result = prime * result + ((this.plantCode == null) ? 0 : this.plantCode.hashCode());
        result = prime * result + ((this.empType == null) ? 0 : this.empType.hashCode());
        result = prime * result + ((this.empName == null) ? 0 : this.empName.hashCode());
        result = prime * result + ((this.companyName == null) ? 0 : this.companyName.hashCode());
        result = prime * result + ((this.department == null) ? 0 : this.department.hashCode());
        result = prime * result + ((this.pointOfContact == null) ? 0 : this.pointOfContact.hashCode());
        result = prime * result + ((this.mealCount == null) ? 0 : this.mealCount.hashCode());
        result = prime * result + ((this.extraCount == null) ? 0 : this.extraCount.hashCode());
        result = prime * result + ((this.totalCount == null) ? 0 : this.totalCount.hashCode());
        result = prime * result + ((this.active == null) ? 0 : this.active.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.lastModifiedBy == null) ? 0 : this.lastModifiedBy.hashCode());
        result = prime * result + ((this.lastModifiedOn == null) ? 0 : this.lastModifiedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CcmsGuestDetailsNew (");

        sb.append(empCode);
        sb.append(", ").append(mealDate);
        sb.append(", ").append(mealShift);
        sb.append(", ").append(plantCode);
        sb.append(", ").append(empType);
        sb.append(", ").append(empName);
        sb.append(", ").append(companyName);
        sb.append(", ").append(department);
        sb.append(", ").append(pointOfContact);
        sb.append(", ").append(mealCount);
        sb.append(", ").append(extraCount);
        sb.append(", ").append(totalCount);
        sb.append(", ").append(active);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(lastModifiedBy);
        sb.append(", ").append(lastModifiedOn);

        sb.append(")");
        return sb.toString();
    }
}
