/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CcmsSecurityTypeMaster implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  securityType;
    private String  securityName;
    private String  status;

    public CcmsSecurityTypeMaster() {}

    public CcmsSecurityTypeMaster(CcmsSecurityTypeMaster value) {
        this.id = value.id;
        this.securityType = value.securityType;
        this.securityName = value.securityName;
        this.status = value.status;
    }

    public CcmsSecurityTypeMaster(
        Integer id,
        String  securityType,
        String  securityName,
        String  status
    ) {
        this.id = id;
        this.securityType = securityType;
        this.securityName = securityName;
        this.status = status;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_security_type_master.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_security_type_master.id</code>.
     */
    public CcmsSecurityTypeMaster setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_security_type_master.security_type</code>.
     */
    public String getSecurityType() {
        return this.securityType;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_security_type_master.security_type</code>.
     */
    public CcmsSecurityTypeMaster setSecurityType(String securityType) {
        this.securityType = securityType;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_security_type_master.security_name</code>.
     */
    public String getSecurityName() {
        return this.securityName;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_security_type_master.security_name</code>.
     */
    public CcmsSecurityTypeMaster setSecurityName(String securityName) {
        this.securityName = securityName;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_security_type_master.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_security_type_master.status</code>.
     */
    public CcmsSecurityTypeMaster setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CcmsSecurityTypeMaster other = (CcmsSecurityTypeMaster) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (securityType == null) {
            if (other.securityType != null)
                return false;
        }
        else if (!securityType.equals(other.securityType))
            return false;
        if (securityName == null) {
            if (other.securityName != null)
                return false;
        }
        else if (!securityName.equals(other.securityName))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.securityType == null) ? 0 : this.securityType.hashCode());
        result = prime * result + ((this.securityName == null) ? 0 : this.securityName.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CcmsSecurityTypeMaster (");

        sb.append(id);
        sb.append(", ").append(securityType);
        sb.append(", ").append(securityName);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
