/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HapPoItemImageUpload implements Serializable {

    private static final long serialVersionUID = 1L;

    private String poNumber;
    private String poItemNo;
    private String poServiceItemNo;
    private String poImage;
    private String poUrl;
    private String imageLatitude;
    private String imageLongitude;

    public HapPoItemImageUpload() {}

    public HapPoItemImageUpload(HapPoItemImageUpload value) {
        this.poNumber = value.poNumber;
        this.poItemNo = value.poItemNo;
        this.poServiceItemNo = value.poServiceItemNo;
        this.poImage = value.poImage;
        this.poUrl = value.poUrl;
        this.imageLatitude = value.imageLatitude;
        this.imageLongitude = value.imageLongitude;
    }

    public HapPoItemImageUpload(
        String poNumber,
        String poItemNo,
        String poServiceItemNo,
        String poImage,
        String poUrl,
        String imageLatitude,
        String imageLongitude
    ) {
        this.poNumber = poNumber;
        this.poItemNo = poItemNo;
        this.poServiceItemNo = poServiceItemNo;
        this.poImage = poImage;
        this.poUrl = poUrl;
        this.imageLatitude = imageLatitude;
        this.imageLongitude = imageLongitude;
    }

    /**
     * Getter for <code>vendor_portal_pbx.hap_po_item_image_upload.PO_NUMBER</code>.
     */
    public String getPoNumber() {
        return this.poNumber;
    }

    /**
     * Setter for <code>vendor_portal_pbx.hap_po_item_image_upload.PO_NUMBER</code>.
     */
    public HapPoItemImageUpload setPoNumber(String poNumber) {
        this.poNumber = poNumber;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.hap_po_item_image_upload.PO_ITEM_NO</code>.
     */
    public String getPoItemNo() {
        return this.poItemNo;
    }

    /**
     * Setter for <code>vendor_portal_pbx.hap_po_item_image_upload.PO_ITEM_NO</code>.
     */
    public HapPoItemImageUpload setPoItemNo(String poItemNo) {
        this.poItemNo = poItemNo;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.hap_po_item_image_upload.PO_SERVICE_ITEM_NO</code>.
     */
    public String getPoServiceItemNo() {
        return this.poServiceItemNo;
    }

    /**
     * Setter for <code>vendor_portal_pbx.hap_po_item_image_upload.PO_SERVICE_ITEM_NO</code>.
     */
    public HapPoItemImageUpload setPoServiceItemNo(String poServiceItemNo) {
        this.poServiceItemNo = poServiceItemNo;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.hap_po_item_image_upload.PO_IMAGE</code>.
     */
    public String getPoImage() {
        return this.poImage;
    }

    /**
     * Setter for <code>vendor_portal_pbx.hap_po_item_image_upload.PO_IMAGE</code>.
     */
    public HapPoItemImageUpload setPoImage(String poImage) {
        this.poImage = poImage;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.hap_po_item_image_upload.PO_URL</code>.
     */
    public String getPoUrl() {
        return this.poUrl;
    }

    /**
     * Setter for <code>vendor_portal_pbx.hap_po_item_image_upload.PO_URL</code>.
     */
    public HapPoItemImageUpload setPoUrl(String poUrl) {
        this.poUrl = poUrl;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.hap_po_item_image_upload.IMAGE_LATITUDE</code>.
     */
    public String getImageLatitude() {
        return this.imageLatitude;
    }

    /**
     * Setter for <code>vendor_portal_pbx.hap_po_item_image_upload.IMAGE_LATITUDE</code>.
     */
    public HapPoItemImageUpload setImageLatitude(String imageLatitude) {
        this.imageLatitude = imageLatitude;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.hap_po_item_image_upload.IMAGE_LONGITUDE</code>.
     */
    public String getImageLongitude() {
        return this.imageLongitude;
    }

    /**
     * Setter for <code>vendor_portal_pbx.hap_po_item_image_upload.IMAGE_LONGITUDE</code>.
     */
    public HapPoItemImageUpload setImageLongitude(String imageLongitude) {
        this.imageLongitude = imageLongitude;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final HapPoItemImageUpload other = (HapPoItemImageUpload) obj;
        if (poNumber == null) {
            if (other.poNumber != null)
                return false;
        }
        else if (!poNumber.equals(other.poNumber))
            return false;
        if (poItemNo == null) {
            if (other.poItemNo != null)
                return false;
        }
        else if (!poItemNo.equals(other.poItemNo))
            return false;
        if (poServiceItemNo == null) {
            if (other.poServiceItemNo != null)
                return false;
        }
        else if (!poServiceItemNo.equals(other.poServiceItemNo))
            return false;
        if (poImage == null) {
            if (other.poImage != null)
                return false;
        }
        else if (!poImage.equals(other.poImage))
            return false;
        if (poUrl == null) {
            if (other.poUrl != null)
                return false;
        }
        else if (!poUrl.equals(other.poUrl))
            return false;
        if (imageLatitude == null) {
            if (other.imageLatitude != null)
                return false;
        }
        else if (!imageLatitude.equals(other.imageLatitude))
            return false;
        if (imageLongitude == null) {
            if (other.imageLongitude != null)
                return false;
        }
        else if (!imageLongitude.equals(other.imageLongitude))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.poNumber == null) ? 0 : this.poNumber.hashCode());
        result = prime * result + ((this.poItemNo == null) ? 0 : this.poItemNo.hashCode());
        result = prime * result + ((this.poServiceItemNo == null) ? 0 : this.poServiceItemNo.hashCode());
        result = prime * result + ((this.poImage == null) ? 0 : this.poImage.hashCode());
        result = prime * result + ((this.poUrl == null) ? 0 : this.poUrl.hashCode());
        result = prime * result + ((this.imageLatitude == null) ? 0 : this.imageLatitude.hashCode());
        result = prime * result + ((this.imageLongitude == null) ? 0 : this.imageLongitude.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HapPoItemImageUpload (");

        sb.append(poNumber);
        sb.append(", ").append(poItemNo);
        sb.append(", ").append(poServiceItemNo);
        sb.append(", ").append(poImage);
        sb.append(", ").append(poUrl);
        sb.append(", ").append(imageLatitude);
        sb.append(", ").append(imageLongitude);

        sb.append(")");
        return sb.toString();
    }
}
