/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IvrCcMaster implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       enquiryTypeId;
    private Integer       optionId;
    private String        enquiryName;
    private String        enquiryVal;
    private String        optionName;
    private String        optionVal;
    private String        status;
    private String        createdBy;
    private LocalDateTime createdOn;
    private String        updatedBy;
    private LocalDateTime updatedOn;

    public IvrCcMaster() {}

    public IvrCcMaster(IvrCcMaster value) {
        this.enquiryTypeId = value.enquiryTypeId;
        this.optionId = value.optionId;
        this.enquiryName = value.enquiryName;
        this.enquiryVal = value.enquiryVal;
        this.optionName = value.optionName;
        this.optionVal = value.optionVal;
        this.status = value.status;
        this.createdBy = value.createdBy;
        this.createdOn = value.createdOn;
        this.updatedBy = value.updatedBy;
        this.updatedOn = value.updatedOn;
    }

    public IvrCcMaster(
        Integer       enquiryTypeId,
        Integer       optionId,
        String        enquiryName,
        String        enquiryVal,
        String        optionName,
        String        optionVal,
        String        status,
        String        createdBy,
        LocalDateTime createdOn,
        String        updatedBy,
        LocalDateTime updatedOn
    ) {
        this.enquiryTypeId = enquiryTypeId;
        this.optionId = optionId;
        this.enquiryName = enquiryName;
        this.enquiryVal = enquiryVal;
        this.optionName = optionName;
        this.optionVal = optionVal;
        this.status = status;
        this.createdBy = createdBy;
        this.createdOn = createdOn;
        this.updatedBy = updatedBy;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_cc_master.ENQUIRY_TYPE_ID</code>.
     */
    public Integer getEnquiryTypeId() {
        return this.enquiryTypeId;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_cc_master.ENQUIRY_TYPE_ID</code>.
     */
    public IvrCcMaster setEnquiryTypeId(Integer enquiryTypeId) {
        this.enquiryTypeId = enquiryTypeId;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_cc_master.OPTION_ID</code>.
     */
    public Integer getOptionId() {
        return this.optionId;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_cc_master.OPTION_ID</code>.
     */
    public IvrCcMaster setOptionId(Integer optionId) {
        this.optionId = optionId;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_cc_master.ENQUIRY_NAME</code>.
     */
    public String getEnquiryName() {
        return this.enquiryName;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_cc_master.ENQUIRY_NAME</code>.
     */
    public IvrCcMaster setEnquiryName(String enquiryName) {
        this.enquiryName = enquiryName;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_cc_master.ENQUIRY_VAL</code>.
     */
    public String getEnquiryVal() {
        return this.enquiryVal;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_cc_master.ENQUIRY_VAL</code>.
     */
    public IvrCcMaster setEnquiryVal(String enquiryVal) {
        this.enquiryVal = enquiryVal;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_cc_master.OPTION_NAME</code>.
     */
    public String getOptionName() {
        return this.optionName;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_cc_master.OPTION_NAME</code>.
     */
    public IvrCcMaster setOptionName(String optionName) {
        this.optionName = optionName;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_cc_master.OPTION_VAL</code>.
     */
    public String getOptionVal() {
        return this.optionVal;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_cc_master.OPTION_VAL</code>.
     */
    public IvrCcMaster setOptionVal(String optionVal) {
        this.optionVal = optionVal;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_cc_master.STATUS</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_cc_master.STATUS</code>.
     */
    public IvrCcMaster setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_cc_master.CREATED_BY</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_cc_master.CREATED_BY</code>.
     */
    public IvrCcMaster setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_cc_master.CREATED_ON</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_cc_master.CREATED_ON</code>.
     */
    public IvrCcMaster setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_cc_master.UPDATED_BY</code>.
     */
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_cc_master.UPDATED_BY</code>.
     */
    public IvrCcMaster setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_cc_master.UPDATED_ON</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_cc_master.UPDATED_ON</code>.
     */
    public IvrCcMaster setUpdatedOn(LocalDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final IvrCcMaster other = (IvrCcMaster) obj;
        if (enquiryTypeId == null) {
            if (other.enquiryTypeId != null)
                return false;
        }
        else if (!enquiryTypeId.equals(other.enquiryTypeId))
            return false;
        if (optionId == null) {
            if (other.optionId != null)
                return false;
        }
        else if (!optionId.equals(other.optionId))
            return false;
        if (enquiryName == null) {
            if (other.enquiryName != null)
                return false;
        }
        else if (!enquiryName.equals(other.enquiryName))
            return false;
        if (enquiryVal == null) {
            if (other.enquiryVal != null)
                return false;
        }
        else if (!enquiryVal.equals(other.enquiryVal))
            return false;
        if (optionName == null) {
            if (other.optionName != null)
                return false;
        }
        else if (!optionName.equals(other.optionName))
            return false;
        if (optionVal == null) {
            if (other.optionVal != null)
                return false;
        }
        else if (!optionVal.equals(other.optionVal))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!createdBy.equals(other.createdBy))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!updatedBy.equals(other.updatedBy))
            return false;
        if (updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.enquiryTypeId == null) ? 0 : this.enquiryTypeId.hashCode());
        result = prime * result + ((this.optionId == null) ? 0 : this.optionId.hashCode());
        result = prime * result + ((this.enquiryName == null) ? 0 : this.enquiryName.hashCode());
        result = prime * result + ((this.enquiryVal == null) ? 0 : this.enquiryVal.hashCode());
        result = prime * result + ((this.optionName == null) ? 0 : this.optionName.hashCode());
        result = prime * result + ((this.optionVal == null) ? 0 : this.optionVal.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IvrCcMaster (");

        sb.append(enquiryTypeId);
        sb.append(", ").append(optionId);
        sb.append(", ").append(enquiryName);
        sb.append(", ").append(enquiryVal);
        sb.append(", ").append(optionName);
        sb.append(", ").append(optionVal);
        sb.append(", ").append(status);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
