/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MilkIncentiveMaster implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        compCode;
    private String        incType;
    private LocalDate     incValidFrom;
    private LocalDate     incValidTo;
    private String        incDescription;
    private String        qtyStructure;
    private String        qulCondition;
    private String        qulCriteria;
    private String        comparistionTy;
    private String        securityDeposit;
    private String        depositPercent;
    private String        status;
    private Integer       createdBy;
    private LocalDateTime createdOn;
    private Integer       lastChangedBy;
    private LocalDateTime lastChangedOn;

    public MilkIncentiveMaster() {}

    public MilkIncentiveMaster(MilkIncentiveMaster value) {
        this.compCode = value.compCode;
        this.incType = value.incType;
        this.incValidFrom = value.incValidFrom;
        this.incValidTo = value.incValidTo;
        this.incDescription = value.incDescription;
        this.qtyStructure = value.qtyStructure;
        this.qulCondition = value.qulCondition;
        this.qulCriteria = value.qulCriteria;
        this.comparistionTy = value.comparistionTy;
        this.securityDeposit = value.securityDeposit;
        this.depositPercent = value.depositPercent;
        this.status = value.status;
        this.createdBy = value.createdBy;
        this.createdOn = value.createdOn;
        this.lastChangedBy = value.lastChangedBy;
        this.lastChangedOn = value.lastChangedOn;
    }

    public MilkIncentiveMaster(
        String        compCode,
        String        incType,
        LocalDate     incValidFrom,
        LocalDate     incValidTo,
        String        incDescription,
        String        qtyStructure,
        String        qulCondition,
        String        qulCriteria,
        String        comparistionTy,
        String        securityDeposit,
        String        depositPercent,
        String        status,
        Integer       createdBy,
        LocalDateTime createdOn,
        Integer       lastChangedBy,
        LocalDateTime lastChangedOn
    ) {
        this.compCode = compCode;
        this.incType = incType;
        this.incValidFrom = incValidFrom;
        this.incValidTo = incValidTo;
        this.incDescription = incDescription;
        this.qtyStructure = qtyStructure;
        this.qulCondition = qulCondition;
        this.qulCriteria = qulCriteria;
        this.comparistionTy = comparistionTy;
        this.securityDeposit = securityDeposit;
        this.depositPercent = depositPercent;
        this.status = status;
        this.createdBy = createdBy;
        this.createdOn = createdOn;
        this.lastChangedBy = lastChangedBy;
        this.lastChangedOn = lastChangedOn;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.COMP_CODE</code>.
     */
    public String getCompCode() {
        return this.compCode;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.COMP_CODE</code>.
     */
    public MilkIncentiveMaster setCompCode(String compCode) {
        this.compCode = compCode;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.INC_TYPE</code>.
     */
    public String getIncType() {
        return this.incType;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.INC_TYPE</code>.
     */
    public MilkIncentiveMaster setIncType(String incType) {
        this.incType = incType;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.INC_VALID_FROM</code>.
     */
    public LocalDate getIncValidFrom() {
        return this.incValidFrom;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.INC_VALID_FROM</code>.
     */
    public MilkIncentiveMaster setIncValidFrom(LocalDate incValidFrom) {
        this.incValidFrom = incValidFrom;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.INC_VALID_TO</code>.
     */
    public LocalDate getIncValidTo() {
        return this.incValidTo;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.INC_VALID_TO</code>.
     */
    public MilkIncentiveMaster setIncValidTo(LocalDate incValidTo) {
        this.incValidTo = incValidTo;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.INC_DESCRIPTION</code>.
     */
    public String getIncDescription() {
        return this.incDescription;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.INC_DESCRIPTION</code>.
     */
    public MilkIncentiveMaster setIncDescription(String incDescription) {
        this.incDescription = incDescription;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.QTY_STRUCTURE</code>.
     */
    public String getQtyStructure() {
        return this.qtyStructure;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.QTY_STRUCTURE</code>.
     */
    public MilkIncentiveMaster setQtyStructure(String qtyStructure) {
        this.qtyStructure = qtyStructure;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.QUL_CONDITION</code>.
     */
    public String getQulCondition() {
        return this.qulCondition;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.QUL_CONDITION</code>.
     */
    public MilkIncentiveMaster setQulCondition(String qulCondition) {
        this.qulCondition = qulCondition;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.QUL_CRITERIA</code>.
     */
    public String getQulCriteria() {
        return this.qulCriteria;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.QUL_CRITERIA</code>.
     */
    public MilkIncentiveMaster setQulCriteria(String qulCriteria) {
        this.qulCriteria = qulCriteria;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.COMPARISTION_TY</code>.
     */
    public String getComparistionTy() {
        return this.comparistionTy;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.COMPARISTION_TY</code>.
     */
    public MilkIncentiveMaster setComparistionTy(String comparistionTy) {
        this.comparistionTy = comparistionTy;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.SECURITY_DEPOSIT</code>.
     */
    public String getSecurityDeposit() {
        return this.securityDeposit;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.SECURITY_DEPOSIT</code>.
     */
    public MilkIncentiveMaster setSecurityDeposit(String securityDeposit) {
        this.securityDeposit = securityDeposit;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.DEPOSIT_PERCENT</code>.
     */
    public String getDepositPercent() {
        return this.depositPercent;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.DEPOSIT_PERCENT</code>.
     */
    public MilkIncentiveMaster setDepositPercent(String depositPercent) {
        this.depositPercent = depositPercent;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.STATUS</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.STATUS</code>.
     */
    public MilkIncentiveMaster setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.CREATED_BY</code>.
     */
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.CREATED_BY</code>.
     */
    public MilkIncentiveMaster setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.CREATED_ON</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.CREATED_ON</code>.
     */
    public MilkIncentiveMaster setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.LAST_CHANGED_BY</code>.
     */
    public Integer getLastChangedBy() {
        return this.lastChangedBy;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.LAST_CHANGED_BY</code>.
     */
    public MilkIncentiveMaster setLastChangedBy(Integer lastChangedBy) {
        this.lastChangedBy = lastChangedBy;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.milk_incentive_master.LAST_CHANGED_ON</code>.
     */
    public LocalDateTime getLastChangedOn() {
        return this.lastChangedOn;
    }

    /**
     * Setter for <code>vendor_portal_pbx.milk_incentive_master.LAST_CHANGED_ON</code>.
     */
    public MilkIncentiveMaster setLastChangedOn(LocalDateTime lastChangedOn) {
        this.lastChangedOn = lastChangedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MilkIncentiveMaster other = (MilkIncentiveMaster) obj;
        if (compCode == null) {
            if (other.compCode != null)
                return false;
        }
        else if (!compCode.equals(other.compCode))
            return false;
        if (incType == null) {
            if (other.incType != null)
                return false;
        }
        else if (!incType.equals(other.incType))
            return false;
        if (incValidFrom == null) {
            if (other.incValidFrom != null)
                return false;
        }
        else if (!incValidFrom.equals(other.incValidFrom))
            return false;
        if (incValidTo == null) {
            if (other.incValidTo != null)
                return false;
        }
        else if (!incValidTo.equals(other.incValidTo))
            return false;
        if (incDescription == null) {
            if (other.incDescription != null)
                return false;
        }
        else if (!incDescription.equals(other.incDescription))
            return false;
        if (qtyStructure == null) {
            if (other.qtyStructure != null)
                return false;
        }
        else if (!qtyStructure.equals(other.qtyStructure))
            return false;
        if (qulCondition == null) {
            if (other.qulCondition != null)
                return false;
        }
        else if (!qulCondition.equals(other.qulCondition))
            return false;
        if (qulCriteria == null) {
            if (other.qulCriteria != null)
                return false;
        }
        else if (!qulCriteria.equals(other.qulCriteria))
            return false;
        if (comparistionTy == null) {
            if (other.comparistionTy != null)
                return false;
        }
        else if (!comparistionTy.equals(other.comparistionTy))
            return false;
        if (securityDeposit == null) {
            if (other.securityDeposit != null)
                return false;
        }
        else if (!securityDeposit.equals(other.securityDeposit))
            return false;
        if (depositPercent == null) {
            if (other.depositPercent != null)
                return false;
        }
        else if (!depositPercent.equals(other.depositPercent))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!createdBy.equals(other.createdBy))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (lastChangedBy == null) {
            if (other.lastChangedBy != null)
                return false;
        }
        else if (!lastChangedBy.equals(other.lastChangedBy))
            return false;
        if (lastChangedOn == null) {
            if (other.lastChangedOn != null)
                return false;
        }
        else if (!lastChangedOn.equals(other.lastChangedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.compCode == null) ? 0 : this.compCode.hashCode());
        result = prime * result + ((this.incType == null) ? 0 : this.incType.hashCode());
        result = prime * result + ((this.incValidFrom == null) ? 0 : this.incValidFrom.hashCode());
        result = prime * result + ((this.incValidTo == null) ? 0 : this.incValidTo.hashCode());
        result = prime * result + ((this.incDescription == null) ? 0 : this.incDescription.hashCode());
        result = prime * result + ((this.qtyStructure == null) ? 0 : this.qtyStructure.hashCode());
        result = prime * result + ((this.qulCondition == null) ? 0 : this.qulCondition.hashCode());
        result = prime * result + ((this.qulCriteria == null) ? 0 : this.qulCriteria.hashCode());
        result = prime * result + ((this.comparistionTy == null) ? 0 : this.comparistionTy.hashCode());
        result = prime * result + ((this.securityDeposit == null) ? 0 : this.securityDeposit.hashCode());
        result = prime * result + ((this.depositPercent == null) ? 0 : this.depositPercent.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.lastChangedBy == null) ? 0 : this.lastChangedBy.hashCode());
        result = prime * result + ((this.lastChangedOn == null) ? 0 : this.lastChangedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MilkIncentiveMaster (");

        sb.append(compCode);
        sb.append(", ").append(incType);
        sb.append(", ").append(incValidFrom);
        sb.append(", ").append(incValidTo);
        sb.append(", ").append(incDescription);
        sb.append(", ").append(qtyStructure);
        sb.append(", ").append(qulCondition);
        sb.append(", ").append(qulCriteria);
        sb.append(", ").append(comparistionTy);
        sb.append(", ").append(securityDeposit);
        sb.append(", ").append(depositPercent);
        sb.append(", ").append(status);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(lastChangedBy);
        sb.append(", ").append(lastChangedOn);

        sb.append(")");
        return sb.toString();
    }
}
