/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReceiptTypeMaster implements Serializable {

    private static final long serialVersionUID = 1L;

    private String no;
    private String receiptName;
    private String receiptValue;
    private String status;

    public ReceiptTypeMaster() {}

    public ReceiptTypeMaster(ReceiptTypeMaster value) {
        this.no = value.no;
        this.receiptName = value.receiptName;
        this.receiptValue = value.receiptValue;
        this.status = value.status;
    }

    public ReceiptTypeMaster(
        String no,
        String receiptName,
        String receiptValue,
        String status
    ) {
        this.no = no;
        this.receiptName = receiptName;
        this.receiptValue = receiptValue;
        this.status = status;
    }

    /**
     * Getter for <code>vendor_portal_pbx.receipt_type_master.NO</code>.
     */
    public String getNo() {
        return this.no;
    }

    /**
     * Setter for <code>vendor_portal_pbx.receipt_type_master.NO</code>.
     */
    public ReceiptTypeMaster setNo(String no) {
        this.no = no;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.receipt_type_master.RECEIPT_NAME</code>.
     */
    public String getReceiptName() {
        return this.receiptName;
    }

    /**
     * Setter for <code>vendor_portal_pbx.receipt_type_master.RECEIPT_NAME</code>.
     */
    public ReceiptTypeMaster setReceiptName(String receiptName) {
        this.receiptName = receiptName;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.receipt_type_master.RECEIPT_VALUE</code>.
     */
    public String getReceiptValue() {
        return this.receiptValue;
    }

    /**
     * Setter for <code>vendor_portal_pbx.receipt_type_master.RECEIPT_VALUE</code>.
     */
    public ReceiptTypeMaster setReceiptValue(String receiptValue) {
        this.receiptValue = receiptValue;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.receipt_type_master.STATUS</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>vendor_portal_pbx.receipt_type_master.STATUS</code>.
     */
    public ReceiptTypeMaster setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReceiptTypeMaster other = (ReceiptTypeMaster) obj;
        if (no == null) {
            if (other.no != null)
                return false;
        }
        else if (!no.equals(other.no))
            return false;
        if (receiptName == null) {
            if (other.receiptName != null)
                return false;
        }
        else if (!receiptName.equals(other.receiptName))
            return false;
        if (receiptValue == null) {
            if (other.receiptValue != null)
                return false;
        }
        else if (!receiptValue.equals(other.receiptValue))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.no == null) ? 0 : this.no.hashCode());
        result = prime * result + ((this.receiptName == null) ? 0 : this.receiptName.hashCode());
        result = prime * result + ((this.receiptValue == null) ? 0 : this.receiptValue.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReceiptTypeMaster (");

        sb.append(no);
        sb.append(", ").append(receiptName);
        sb.append(", ").append(receiptValue);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
