/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleAccess implements Serializable {

    private static final long serialVersionUID = 1L;

    private String  compCode;
    private Integer roleId;
    private Integer menuOrderId;
    private Integer menuId;
    private String  block;
    private String  type;

    public RoleAccess() {}

    public RoleAccess(RoleAccess value) {
        this.compCode = value.compCode;
        this.roleId = value.roleId;
        this.menuOrderId = value.menuOrderId;
        this.menuId = value.menuId;
        this.block = value.block;
        this.type = value.type;
    }

    public RoleAccess(
        String  compCode,
        Integer roleId,
        Integer menuOrderId,
        Integer menuId,
        String  block,
        String  type
    ) {
        this.compCode = compCode;
        this.roleId = roleId;
        this.menuOrderId = menuOrderId;
        this.menuId = menuId;
        this.block = block;
        this.type = type;
    }

    /**
     * Getter for <code>vendor_portal_pbx.role_access.COMP_CODE</code>.
     */
    public String getCompCode() {
        return this.compCode;
    }

    /**
     * Setter for <code>vendor_portal_pbx.role_access.COMP_CODE</code>.
     */
    public RoleAccess setCompCode(String compCode) {
        this.compCode = compCode;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.role_access.ROLE_ID</code>.
     */
    public Integer getRoleId() {
        return this.roleId;
    }

    /**
     * Setter for <code>vendor_portal_pbx.role_access.ROLE_ID</code>.
     */
    public RoleAccess setRoleId(Integer roleId) {
        this.roleId = roleId;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.role_access.MENU_ORDER_ID</code>.
     */
    public Integer getMenuOrderId() {
        return this.menuOrderId;
    }

    /**
     * Setter for <code>vendor_portal_pbx.role_access.MENU_ORDER_ID</code>.
     */
    public RoleAccess setMenuOrderId(Integer menuOrderId) {
        this.menuOrderId = menuOrderId;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.role_access.MENU_ID</code>.
     */
    public Integer getMenuId() {
        return this.menuId;
    }

    /**
     * Setter for <code>vendor_portal_pbx.role_access.MENU_ID</code>.
     */
    public RoleAccess setMenuId(Integer menuId) {
        this.menuId = menuId;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.role_access.BLOCK</code>.
     */
    public String getBlock() {
        return this.block;
    }

    /**
     * Setter for <code>vendor_portal_pbx.role_access.BLOCK</code>.
     */
    public RoleAccess setBlock(String block) {
        this.block = block;
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.role_access.TYPE</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>vendor_portal_pbx.role_access.TYPE</code>.
     */
    public RoleAccess setType(String type) {
        this.type = type;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RoleAccess other = (RoleAccess) obj;
        if (compCode == null) {
            if (other.compCode != null)
                return false;
        }
        else if (!compCode.equals(other.compCode))
            return false;
        if (roleId == null) {
            if (other.roleId != null)
                return false;
        }
        else if (!roleId.equals(other.roleId))
            return false;
        if (menuOrderId == null) {
            if (other.menuOrderId != null)
                return false;
        }
        else if (!menuOrderId.equals(other.menuOrderId))
            return false;
        if (menuId == null) {
            if (other.menuId != null)
                return false;
        }
        else if (!menuId.equals(other.menuId))
            return false;
        if (block == null) {
            if (other.block != null)
                return false;
        }
        else if (!block.equals(other.block))
            return false;
        if (type == null) {
            if (other.type != null)
                return false;
        }
        else if (!type.equals(other.type))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.compCode == null) ? 0 : this.compCode.hashCode());
        result = prime * result + ((this.roleId == null) ? 0 : this.roleId.hashCode());
        result = prime * result + ((this.menuOrderId == null) ? 0 : this.menuOrderId.hashCode());
        result = prime * result + ((this.menuId == null) ? 0 : this.menuId.hashCode());
        result = prime * result + ((this.block == null) ? 0 : this.block.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RoleAccess (");

        sb.append(compCode);
        sb.append(", ").append(roleId);
        sb.append(", ").append(menuOrderId);
        sb.append(", ").append(menuId);
        sb.append(", ").append(block);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
