/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables;


import com.jooq.jooq.model.Keys;
import com.jooq.jooq.model.VendorPortalPbx;
import com.jooq.jooq.model.tables.records.CcMailCustomerHierarchyRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CcMailCustomerHierarchy extends TableImpl<CcMailCustomerHierarchyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>vendor_portal_pbx.cc_mail_customer_hierarchy</code>
     */
    public static final CcMailCustomerHierarchy CC_MAIL_CUSTOMER_HIERARCHY = new CcMailCustomerHierarchy();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CcMailCustomerHierarchyRecord> getRecordType() {
        return CcMailCustomerHierarchyRecord.class;
    }

    /**
     * The column <code>vendor_portal_pbx.cc_mail_customer_hierarchy.SNO</code>.
     */
    public final TableField<CcMailCustomerHierarchyRecord, Integer> SNO = createField(DSL.name("SNO"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>vendor_portal_pbx.cc_mail_customer_hierarchy.DIVISION</code>.
     */
    public final TableField<CcMailCustomerHierarchyRecord, String> DIVISION = createField(DSL.name("DIVISION"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.cc_mail_customer_hierarchy.EMP_NAME</code>.
     */
    public final TableField<CcMailCustomerHierarchyRecord, String> EMP_NAME = createField(DSL.name("EMP_NAME"), SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>vendor_portal_pbx.cc_mail_customer_hierarchy.DESIGNATION</code>.
     */
    public final TableField<CcMailCustomerHierarchyRecord, String> DESIGNATION = createField(DSL.name("DESIGNATION"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.cc_mail_customer_hierarchy.LOCATION</code>.
     */
    public final TableField<CcMailCustomerHierarchyRecord, String> LOCATION = createField(DSL.name("LOCATION"), SQLDataType.VARCHAR(250), this, "");

    /**
     * The column <code>vendor_portal_pbx.cc_mail_customer_hierarchy.MOBILE_NO</code>.
     */
    public final TableField<CcMailCustomerHierarchyRecord, String> MOBILE_NO = createField(DSL.name("MOBILE_NO"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.cc_mail_customer_hierarchy.EMAIL</code>.
     */
    public final TableField<CcMailCustomerHierarchyRecord, String> EMAIL = createField(DSL.name("EMAIL"), SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>vendor_portal_pbx.cc_mail_customer_hierarchy.CREATED_BY</code>.
     */
    public final TableField<CcMailCustomerHierarchyRecord, String> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.cc_mail_customer_hierarchy.CREATED_ON</code>.
     */
    public final TableField<CcMailCustomerHierarchyRecord, LocalDateTime> CREATED_ON = createField(DSL.name("CREATED_ON"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>vendor_portal_pbx.cc_mail_customer_hierarchy.STATUS</code>.
     */
    public final TableField<CcMailCustomerHierarchyRecord, String> STATUS = createField(DSL.name("STATUS"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>vendor_portal_pbx.cc_mail_customer_hierarchy.FLAG</code>.
     */
    public final TableField<CcMailCustomerHierarchyRecord, String> FLAG = createField(DSL.name("FLAG"), SQLDataType.VARCHAR(1), this, "");

    private CcMailCustomerHierarchy(Name alias, Table<CcMailCustomerHierarchyRecord> aliased) {
        this(alias, aliased, null);
    }

    private CcMailCustomerHierarchy(Name alias, Table<CcMailCustomerHierarchyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.cc_mail_customer_hierarchy</code> table reference
     */
    public CcMailCustomerHierarchy(String alias) {
        this(DSL.name(alias), CC_MAIL_CUSTOMER_HIERARCHY);
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.cc_mail_customer_hierarchy</code> table reference
     */
    public CcMailCustomerHierarchy(Name alias) {
        this(alias, CC_MAIL_CUSTOMER_HIERARCHY);
    }

    /**
     * Create a <code>vendor_portal_pbx.cc_mail_customer_hierarchy</code> table reference
     */
    public CcMailCustomerHierarchy() {
        this(DSL.name("cc_mail_customer_hierarchy"), null);
    }

    public <O extends Record> CcMailCustomerHierarchy(Table<O> child, ForeignKey<O, CcMailCustomerHierarchyRecord> key) {
        super(child, key, CC_MAIL_CUSTOMER_HIERARCHY);
    }

    @Override
    public Schema getSchema() {
        return VendorPortalPbx.VENDOR_PORTAL_PBX;
    }

    @Override
    public Identity<CcMailCustomerHierarchyRecord, Integer> getIdentity() {
        return (Identity<CcMailCustomerHierarchyRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<CcMailCustomerHierarchyRecord> getPrimaryKey() {
        return Keys.KEY_CC_MAIL_CUSTOMER_HIERARCHY_PRIMARY;
    }

    @Override
    public List<UniqueKey<CcMailCustomerHierarchyRecord>> getKeys() {
        return Arrays.<UniqueKey<CcMailCustomerHierarchyRecord>>asList(Keys.KEY_CC_MAIL_CUSTOMER_HIERARCHY_PRIMARY);
    }

    @Override
    public CcMailCustomerHierarchy as(String alias) {
        return new CcMailCustomerHierarchy(DSL.name(alias), this);
    }

    @Override
    public CcMailCustomerHierarchy as(Name alias) {
        return new CcMailCustomerHierarchy(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CcMailCustomerHierarchy rename(String name) {
        return new CcMailCustomerHierarchy(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CcMailCustomerHierarchy rename(Name name) {
        return new CcMailCustomerHierarchy(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, String, String, String, String, String, String, String, LocalDateTime, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
