/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables;


import com.jooq.jooq.model.Keys;
import com.jooq.jooq.model.VendorPortalPbx;
import com.jooq.jooq.model.tables.records.CcmsTabUserMasterRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CcmsTabUserMaster extends TableImpl<CcmsTabUserMasterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>vendor_portal_pbx.ccms_tab_user_master</code>
     */
    public static final CcmsTabUserMaster CCMS_TAB_USER_MASTER = new CcmsTabUserMaster();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CcmsTabUserMasterRecord> getRecordType() {
        return CcmsTabUserMasterRecord.class;
    }

    /**
     * The column <code>vendor_portal_pbx.ccms_tab_user_master.email</code>.
     */
    public final TableField<CcmsTabUserMasterRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_tab_user_master.plant_code</code>.
     */
    public final TableField<CcmsTabUserMasterRecord, String> PLANT_CODE = createField(DSL.name("plant_code"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_tab_user_master.device_id</code>.
     */
    public final TableField<CcmsTabUserMasterRecord, String> DEVICE_ID = createField(DSL.name("device_id"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_tab_user_master.imei_one</code>.
     */
    public final TableField<CcmsTabUserMasterRecord, String> IMEI_ONE = createField(DSL.name("imei_one"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_tab_user_master.imei_two</code>.
     */
    public final TableField<CcmsTabUserMasterRecord, String> IMEI_TWO = createField(DSL.name("imei_two"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_tab_user_master.latitute</code>.
     */
    public final TableField<CcmsTabUserMasterRecord, String> LATITUTE = createField(DSL.name("latitute"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_tab_user_master.longitute</code>.
     */
    public final TableField<CcmsTabUserMasterRecord, String> LONGITUTE = createField(DSL.name("longitute"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_tab_user_master.created_by</code>.
     */
    public final TableField<CcmsTabUserMasterRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_tab_user_master.created_on</code>.
     */
    public final TableField<CcmsTabUserMasterRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_tab_user_master.last_changed_on</code>.
     */
    public final TableField<CcmsTabUserMasterRecord, LocalDateTime> LAST_CHANGED_ON = createField(DSL.name("last_changed_on"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_tab_user_master.last_changed_by</code>.
     */
    public final TableField<CcmsTabUserMasterRecord, String> LAST_CHANGED_BY = createField(DSL.name("last_changed_by"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_tab_user_master.status</code>.
     */
    public final TableField<CcmsTabUserMasterRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_tab_user_master.password</code>.
     */
    public final TableField<CcmsTabUserMasterRecord, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_tab_user_master.user_type_id</code>.
     */
    public final TableField<CcmsTabUserMasterRecord, Integer> USER_TYPE_ID = createField(DSL.name("user_type_id"), SQLDataType.INTEGER, this, "");

    private CcmsTabUserMaster(Name alias, Table<CcmsTabUserMasterRecord> aliased) {
        this(alias, aliased, null);
    }

    private CcmsTabUserMaster(Name alias, Table<CcmsTabUserMasterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.ccms_tab_user_master</code> table reference
     */
    public CcmsTabUserMaster(String alias) {
        this(DSL.name(alias), CCMS_TAB_USER_MASTER);
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.ccms_tab_user_master</code> table reference
     */
    public CcmsTabUserMaster(Name alias) {
        this(alias, CCMS_TAB_USER_MASTER);
    }

    /**
     * Create a <code>vendor_portal_pbx.ccms_tab_user_master</code> table reference
     */
    public CcmsTabUserMaster() {
        this(DSL.name("ccms_tab_user_master"), null);
    }

    public <O extends Record> CcmsTabUserMaster(Table<O> child, ForeignKey<O, CcmsTabUserMasterRecord> key) {
        super(child, key, CCMS_TAB_USER_MASTER);
    }

    @Override
    public Schema getSchema() {
        return VendorPortalPbx.VENDOR_PORTAL_PBX;
    }

    @Override
    public UniqueKey<CcmsTabUserMasterRecord> getPrimaryKey() {
        return Keys.KEY_CCMS_TAB_USER_MASTER_PRIMARY;
    }

    @Override
    public List<UniqueKey<CcmsTabUserMasterRecord>> getKeys() {
        return Arrays.<UniqueKey<CcmsTabUserMasterRecord>>asList(Keys.KEY_CCMS_TAB_USER_MASTER_PRIMARY);
    }

    @Override
    public CcmsTabUserMaster as(String alias) {
        return new CcmsTabUserMaster(DSL.name(alias), this);
    }

    @Override
    public CcmsTabUserMaster as(Name alias) {
        return new CcmsTabUserMaster(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CcmsTabUserMaster rename(String name) {
        return new CcmsTabUserMaster(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CcmsTabUserMaster rename(Name name) {
        return new CcmsTabUserMaster(name, null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String, Integer> fieldsRow() {
        return (Row14) super.fieldsRow();
    }
}
