/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables;


import com.jooq.jooq.model.Keys;
import com.jooq.jooq.model.VendorPortalPbx;
import com.jooq.jooq.model.tables.records.CcmsStatePlantMappingRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CcmsStatePlantMapping extends TableImpl<CcmsStatePlantMappingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>vendor_portal_pbx.ccms_state_plant_mapping</code>
     */
    public static final CcmsStatePlantMapping CCMS_STATE_PLANT_MAPPING = new CcmsStatePlantMapping();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CcmsStatePlantMappingRecord> getRecordType() {
        return CcmsStatePlantMappingRecord.class;
    }

    /**
     * The column <code>vendor_portal_pbx.ccms_state_plant_mapping.state</code>.
     */
    public final TableField<CcmsStatePlantMappingRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_state_plant_mapping.plant</code>.
     */
    public final TableField<CcmsStatePlantMappingRecord, String> PLANT = createField(DSL.name("plant"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_state_plant_mapping.status</code>.
     */
    public final TableField<CcmsStatePlantMappingRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_state_plant_mapping.created_by</code>.
     */
    public final TableField<CcmsStatePlantMappingRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_state_plant_mapping.created_on</code>.
     */
    public final TableField<CcmsStatePlantMappingRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_state_plant_mapping.last_changed_by</code>.
     */
    public final TableField<CcmsStatePlantMappingRecord, String> LAST_CHANGED_BY = createField(DSL.name("last_changed_by"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.ccms_state_plant_mapping.last_changed_on</code>.
     */
    public final TableField<CcmsStatePlantMappingRecord, LocalDateTime> LAST_CHANGED_ON = createField(DSL.name("last_changed_on"), SQLDataType.LOCALDATETIME(0), this, "");

    private CcmsStatePlantMapping(Name alias, Table<CcmsStatePlantMappingRecord> aliased) {
        this(alias, aliased, null);
    }

    private CcmsStatePlantMapping(Name alias, Table<CcmsStatePlantMappingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.ccms_state_plant_mapping</code> table reference
     */
    public CcmsStatePlantMapping(String alias) {
        this(DSL.name(alias), CCMS_STATE_PLANT_MAPPING);
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.ccms_state_plant_mapping</code> table reference
     */
    public CcmsStatePlantMapping(Name alias) {
        this(alias, CCMS_STATE_PLANT_MAPPING);
    }

    /**
     * Create a <code>vendor_portal_pbx.ccms_state_plant_mapping</code> table reference
     */
    public CcmsStatePlantMapping() {
        this(DSL.name("ccms_state_plant_mapping"), null);
    }

    public <O extends Record> CcmsStatePlantMapping(Table<O> child, ForeignKey<O, CcmsStatePlantMappingRecord> key) {
        super(child, key, CCMS_STATE_PLANT_MAPPING);
    }

    @Override
    public Schema getSchema() {
        return VendorPortalPbx.VENDOR_PORTAL_PBX;
    }

    @Override
    public UniqueKey<CcmsStatePlantMappingRecord> getPrimaryKey() {
        return Keys.KEY_CCMS_STATE_PLANT_MAPPING_PRIMARY;
    }

    @Override
    public List<UniqueKey<CcmsStatePlantMappingRecord>> getKeys() {
        return Arrays.<UniqueKey<CcmsStatePlantMappingRecord>>asList(Keys.KEY_CCMS_STATE_PLANT_MAPPING_PRIMARY);
    }

    @Override
    public CcmsStatePlantMapping as(String alias) {
        return new CcmsStatePlantMapping(DSL.name(alias), this);
    }

    @Override
    public CcmsStatePlantMapping as(Name alias) {
        return new CcmsStatePlantMapping(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CcmsStatePlantMapping rename(String name) {
        return new CcmsStatePlantMapping(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CcmsStatePlantMapping rename(Name name) {
        return new CcmsStatePlantMapping(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
