/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables;


import com.jooq.jooq.model.Indexes;
import com.jooq.jooq.model.Keys;
import com.jooq.jooq.model.VendorPortalPbx;
import com.jooq.jooq.model.tables.records.CustomerHmboRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerHmbo extends TableImpl<CustomerHmboRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>vendor_portal_pbx.customer_hmbo</code>
     */
    public static final CustomerHmbo CUSTOMER_HMBO = new CustomerHmbo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomerHmboRecord> getRecordType() {
        return CustomerHmboRecord.class;
    }

    /**
     * The column <code>vendor_portal_pbx.customer_hmbo.COMP_CODE</code>.
     */
    public final TableField<CustomerHmboRecord, String> COMP_CODE = createField(DSL.name("COMP_CODE"), SQLDataType.VARCHAR(4).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.customer_hmbo.CUSTOMER_CODE</code>.
     */
    public final TableField<CustomerHmboRecord, String> CUSTOMER_CODE = createField(DSL.name("CUSTOMER_CODE"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.customer_hmbo.VENDOR_CODE</code>.
     */
    public final TableField<CustomerHmboRecord, String> VENDOR_CODE = createField(DSL.name("VENDOR_CODE"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.customer_hmbo.VENDOR_ACC_GRP_CODE</code>.
     */
    public final TableField<CustomerHmboRecord, String> VENDOR_ACC_GRP_CODE = createField(DSL.name("VENDOR_ACC_GRP_CODE"), SQLDataType.VARCHAR(4).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.customer_hmbo.RR_NO</code>.
     */
    public final TableField<CustomerHmboRecord, String> RR_NO = createField(DSL.name("RR_NO"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.customer_hmbo.ACC_ID</code>.
     */
    public final TableField<CustomerHmboRecord, String> ACC_ID = createField(DSL.name("ACC_ID"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.customer_hmbo.VENDOR_STATUS</code>.
     */
    public final TableField<CustomerHmboRecord, String> VENDOR_STATUS = createField(DSL.name("VENDOR_STATUS"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>vendor_portal_pbx.customer_hmbo.CREATED_ON</code>.
     */
    public final TableField<CustomerHmboRecord, LocalDateTime> CREATED_ON = createField(DSL.name("CREATED_ON"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>vendor_portal_pbx.customer_hmbo.CREATED_BY</code>.
     */
    public final TableField<CustomerHmboRecord, String> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.customer_hmbo.CHANGED_ON</code>.
     */
    public final TableField<CustomerHmboRecord, LocalDateTime> CHANGED_ON = createField(DSL.name("CHANGED_ON"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>vendor_portal_pbx.customer_hmbo.CHANGED_BY</code>.
     */
    public final TableField<CustomerHmboRecord, String> CHANGED_BY = createField(DSL.name("CHANGED_BY"), SQLDataType.VARCHAR(45), this, "");

    private CustomerHmbo(Name alias, Table<CustomerHmboRecord> aliased) {
        this(alias, aliased, null);
    }

    private CustomerHmbo(Name alias, Table<CustomerHmboRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.customer_hmbo</code> table reference
     */
    public CustomerHmbo(String alias) {
        this(DSL.name(alias), CUSTOMER_HMBO);
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.customer_hmbo</code> table reference
     */
    public CustomerHmbo(Name alias) {
        this(alias, CUSTOMER_HMBO);
    }

    /**
     * Create a <code>vendor_portal_pbx.customer_hmbo</code> table reference
     */
    public CustomerHmbo() {
        this(DSL.name("customer_hmbo"), null);
    }

    public <O extends Record> CustomerHmbo(Table<O> child, ForeignKey<O, CustomerHmboRecord> key) {
        super(child, key, CUSTOMER_HMBO);
    }

    @Override
    public Schema getSchema() {
        return VendorPortalPbx.VENDOR_PORTAL_PBX;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CUSTOMER_HMBO_CUSTOMER_CODE_INDEX);
    }

    @Override
    public UniqueKey<CustomerHmboRecord> getPrimaryKey() {
        return Keys.KEY_CUSTOMER_HMBO_PRIMARY;
    }

    @Override
    public List<UniqueKey<CustomerHmboRecord>> getKeys() {
        return Arrays.<UniqueKey<CustomerHmboRecord>>asList(Keys.KEY_CUSTOMER_HMBO_PRIMARY);
    }

    @Override
    public CustomerHmbo as(String alias) {
        return new CustomerHmbo(DSL.name(alias), this);
    }

    @Override
    public CustomerHmbo as(Name alias) {
        return new CustomerHmbo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerHmbo rename(String name) {
        return new CustomerHmbo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerHmbo rename(Name name) {
        return new CustomerHmbo(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
