/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables;


import com.jooq.jooq.model.Keys;
import com.jooq.jooq.model.VendorPortalPbx;
import com.jooq.jooq.model.tables.records.FeedInvoiceLineitemRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeedInvoiceLineitem extends TableImpl<FeedInvoiceLineitemRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>vendor_portal_pbx.feed_invoice_lineitem</code>
     */
    public static final FeedInvoiceLineitem FEED_INVOICE_LINEITEM = new FeedInvoiceLineitem();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FeedInvoiceLineitemRecord> getRecordType() {
        return FeedInvoiceLineitemRecord.class;
    }

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.invoice_no</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> INVOICE_NO = createField(DSL.name("invoice_no"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.line_item_no</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> LINE_ITEM_NO = createField(DSL.name("line_item_no"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.material_no</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> MATERIAL_NO = createField(DSL.name("material_no"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.material_desc</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> MATERIAL_DESC = createField(DSL.name("material_desc"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.ctrl_code</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> CTRL_CODE = createField(DSL.name("ctrl_code"), SQLDataType.VARCHAR(16), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.qty</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> QTY = createField(DSL.name("qty"), SQLDataType.VARCHAR(13), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.custom_qty</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> CUSTOM_QTY = createField(DSL.name("custom_qty"), SQLDataType.VARCHAR(13), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.custom_qty_date</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, LocalDateTime> CUSTOM_QTY_DATE = createField(DSL.name("custom_qty_date"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.confirm_quantity</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> CONFIRM_QUANTITY = createField(DSL.name("confirm_quantity"), SQLDataType.VARCHAR(13), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.confirm_qty_date</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, LocalDateTime> CONFIRM_QTY_DATE = createField(DSL.name("confirm_qty_date"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.delayed_quantity</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> DELAYED_QUANTITY = createField(DSL.name("delayed_quantity"), SQLDataType.VARCHAR(13).defaultValue(DSL.inline("0.0", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.unit</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> UNIT = createField(DSL.name("unit"), SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.amount_or_percentage</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> AMOUNT_OR_PERCENTAGE = createField(DSL.name("amount_or_percentage"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.value</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(13), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.status</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.flag</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> FLAG = createField(DSL.name("flag"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.reason</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> REASON = createField(DSL.name("reason"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.reason_desc</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> REASON_DESC = createField(DSL.name("reason_desc"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.expected_date</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> EXPECTED_DATE = createField(DSL.name("expected_date"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.created_on</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.created_by</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.last_changed_on</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, LocalDateTime> LAST_CHANGED_ON = createField(DSL.name("last_changed_on"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.last_changed_by</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> LAST_CHANGED_BY = createField(DSL.name("last_changed_by"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.feed_invoice_lineitem.remarks</code>.
     */
    public final TableField<FeedInvoiceLineitemRecord, String> REMARKS = createField(DSL.name("remarks"), SQLDataType.VARCHAR(255), this, "");

    private FeedInvoiceLineitem(Name alias, Table<FeedInvoiceLineitemRecord> aliased) {
        this(alias, aliased, null);
    }

    private FeedInvoiceLineitem(Name alias, Table<FeedInvoiceLineitemRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.feed_invoice_lineitem</code> table reference
     */
    public FeedInvoiceLineitem(String alias) {
        this(DSL.name(alias), FEED_INVOICE_LINEITEM);
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.feed_invoice_lineitem</code> table reference
     */
    public FeedInvoiceLineitem(Name alias) {
        this(alias, FEED_INVOICE_LINEITEM);
    }

    /**
     * Create a <code>vendor_portal_pbx.feed_invoice_lineitem</code> table reference
     */
    public FeedInvoiceLineitem() {
        this(DSL.name("feed_invoice_lineitem"), null);
    }

    public <O extends Record> FeedInvoiceLineitem(Table<O> child, ForeignKey<O, FeedInvoiceLineitemRecord> key) {
        super(child, key, FEED_INVOICE_LINEITEM);
    }

    @Override
    public Schema getSchema() {
        return VendorPortalPbx.VENDOR_PORTAL_PBX;
    }

    @Override
    public UniqueKey<FeedInvoiceLineitemRecord> getPrimaryKey() {
        return Keys.KEY_FEED_INVOICE_LINEITEM_PRIMARY;
    }

    @Override
    public List<UniqueKey<FeedInvoiceLineitemRecord>> getKeys() {
        return Arrays.<UniqueKey<FeedInvoiceLineitemRecord>>asList(Keys.KEY_FEED_INVOICE_LINEITEM_PRIMARY);
    }

    @Override
    public FeedInvoiceLineitem as(String alias) {
        return new FeedInvoiceLineitem(DSL.name(alias), this);
    }

    @Override
    public FeedInvoiceLineitem as(Name alias) {
        return new FeedInvoiceLineitem(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedInvoiceLineitem rename(String name) {
        return new FeedInvoiceLineitem(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FeedInvoiceLineitem rename(Name name) {
        return new FeedInvoiceLineitem(name, null);
    }
}
