/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables;


import com.jooq.jooq.model.Keys;
import com.jooq.jooq.model.VendorPortalPbx;
import com.jooq.jooq.model.tables.records.HapPoItemServiceMmRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row21;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HapPoItemServiceMm extends TableImpl<HapPoItemServiceMmRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>vendor_portal_pbx.hap_po_item_service_mm</code>
     */
    public static final HapPoItemServiceMm HAP_PO_ITEM_SERVICE_MM = new HapPoItemServiceMm();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HapPoItemServiceMmRecord> getRecordType() {
        return HapPoItemServiceMmRecord.class;
    }

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.COMP_CODE</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, String> COMP_CODE = createField(DSL.name("COMP_CODE"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.PO_NUMBER</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, String> PO_NUMBER = createField(DSL.name("PO_NUMBER"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.PO_ITEM_NO</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, String> PO_ITEM_NO = createField(DSL.name("PO_ITEM_NO"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.PO_SERVICE_NO</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, String> PO_SERVICE_NO = createField(DSL.name("PO_SERVICE_NO"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.QUANTITY</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, BigDecimal> QUANTITY = createField(DSL.name("QUANTITY"), SQLDataType.DECIMAL(13, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.CONFIRM_QUANTITY</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, BigDecimal> CONFIRM_QUANTITY = createField(DSL.name("CONFIRM_QUANTITY"), SQLDataType.DECIMAL(13, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.DEVIATED_QUANTITY</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, BigDecimal> DEVIATED_QUANTITY = createField(DSL.name("DEVIATED_QUANTITY"), SQLDataType.DECIMAL(13, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.DEVIATED_QUANTITY_REASON</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, String> DEVIATED_QUANTITY_REASON = createField(DSL.name("DEVIATED_QUANTITY_REASON"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.BASE_UOM</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, String> BASE_UOM = createField(DSL.name("BASE_UOM"), SQLDataType.VARCHAR(5), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.PRICE_UNIT</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, BigDecimal> PRICE_UNIT = createField(DSL.name("PRICE_UNIT"), SQLDataType.DECIMAL(13, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.GROSS_VAL</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, BigDecimal> GROSS_VAL = createField(DSL.name("GROSS_VAL"), SQLDataType.DECIMAL(13, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.NET_VALUE</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, BigDecimal> NET_VALUE = createField(DSL.name("NET_VALUE"), SQLDataType.DECIMAL(13, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.SHORT_TEXT</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, String> SHORT_TEXT = createField(DSL.name("SHORT_TEXT"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.LONG_TEXT</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, String> LONG_TEXT = createField(DSL.name("LONG_TEXT"), SQLDataType.VARCHAR(1000), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.MAKE</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, String> MAKE = createField(DSL.name("MAKE"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.SELECTED_MAKE</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, String> SELECTED_MAKE = createField(DSL.name("SELECTED_MAKE"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.DEVIATED_MAKE_REASON</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, String> DEVIATED_MAKE_REASON = createField(DSL.name("DEVIATED_MAKE_REASON"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.CREATED_BY</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, String> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.CREATED_ON</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, LocalDateTime> CREATED_ON = createField(DSL.name("CREATED_ON"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.LAST_CHANGED_BY</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, String> LAST_CHANGED_BY = createField(DSL.name("LAST_CHANGED_BY"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.hap_po_item_service_mm.LAST_CHANGED_ON</code>.
     */
    public final TableField<HapPoItemServiceMmRecord, LocalDateTime> LAST_CHANGED_ON = createField(DSL.name("LAST_CHANGED_ON"), SQLDataType.LOCALDATETIME(0), this, "");

    private HapPoItemServiceMm(Name alias, Table<HapPoItemServiceMmRecord> aliased) {
        this(alias, aliased, null);
    }

    private HapPoItemServiceMm(Name alias, Table<HapPoItemServiceMmRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.hap_po_item_service_mm</code> table reference
     */
    public HapPoItemServiceMm(String alias) {
        this(DSL.name(alias), HAP_PO_ITEM_SERVICE_MM);
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.hap_po_item_service_mm</code> table reference
     */
    public HapPoItemServiceMm(Name alias) {
        this(alias, HAP_PO_ITEM_SERVICE_MM);
    }

    /**
     * Create a <code>vendor_portal_pbx.hap_po_item_service_mm</code> table reference
     */
    public HapPoItemServiceMm() {
        this(DSL.name("hap_po_item_service_mm"), null);
    }

    public <O extends Record> HapPoItemServiceMm(Table<O> child, ForeignKey<O, HapPoItemServiceMmRecord> key) {
        super(child, key, HAP_PO_ITEM_SERVICE_MM);
    }

    @Override
    public Schema getSchema() {
        return VendorPortalPbx.VENDOR_PORTAL_PBX;
    }

    @Override
    public UniqueKey<HapPoItemServiceMmRecord> getPrimaryKey() {
        return Keys.KEY_HAP_PO_ITEM_SERVICE_MM_PRIMARY;
    }

    @Override
    public List<UniqueKey<HapPoItemServiceMmRecord>> getKeys() {
        return Arrays.<UniqueKey<HapPoItemServiceMmRecord>>asList(Keys.KEY_HAP_PO_ITEM_SERVICE_MM_PRIMARY);
    }

    @Override
    public List<ForeignKey<HapPoItemServiceMmRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<HapPoItemServiceMmRecord, ?>>asList(Keys.FK_HAP_PO_ITEM_PO_ITEM_SERVICE_MM);
    }

    private transient HapPoItem _hapPoItem;

    public HapPoItem hapPoItem() {
        if (_hapPoItem == null)
            _hapPoItem = new HapPoItem(this, Keys.FK_HAP_PO_ITEM_PO_ITEM_SERVICE_MM);

        return _hapPoItem;
    }

    @Override
    public HapPoItemServiceMm as(String alias) {
        return new HapPoItemServiceMm(DSL.name(alias), this);
    }

    @Override
    public HapPoItemServiceMm as(Name alias) {
        return new HapPoItemServiceMm(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public HapPoItemServiceMm rename(String name) {
        return new HapPoItemServiceMm(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HapPoItemServiceMm rename(Name name) {
        return new HapPoItemServiceMm(name, null);
    }

    // -------------------------------------------------------------------------
    // Row21 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row21<String, String, String, String, BigDecimal, BigDecimal, BigDecimal, String, String, BigDecimal, BigDecimal, BigDecimal, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row21) super.fieldsRow();
    }
}
