/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables;


import com.jooq.jooq.model.Keys;
import com.jooq.jooq.model.VendorPortalPbx;
import com.jooq.jooq.model.tables.records.HmbServiceDeductionRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HmbServiceDeduction extends TableImpl<HmbServiceDeductionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>vendor_portal_pbx.hmb_service_deduction</code>
     */
    public static final HmbServiceDeduction HMB_SERVICE_DEDUCTION = new HmbServiceDeduction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HmbServiceDeductionRecord> getRecordType() {
        return HmbServiceDeductionRecord.class;
    }

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.COMP_CODE</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> COMP_CODE = createField(DSL.name("COMP_CODE"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZDOCNO</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZDOCNO = createField(DSL.name("ZDOCNO"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZDOCITEM</code>.
     */
    public final TableField<HmbServiceDeductionRecord, Integer> ZDOCITEM = createField(DSL.name("ZDOCITEM"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZDEDTYPE</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZDEDTYPE = createField(DSL.name("ZDEDTYPE"), SQLDataType.VARCHAR(4), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZLOANTYPE</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZLOANTYPE = createField(DSL.name("ZLOANTYPE"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZEDATE</code>.
     */
    public final TableField<HmbServiceDeductionRecord, LocalDate> ZEDATE = createField(DSL.name("ZEDATE"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZSEQUENCE</code>.
     */
    public final TableField<HmbServiceDeductionRecord, Integer> ZSEQUENCE = createField(DSL.name("ZSEQUENCE"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZVENDOR</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZVENDOR = createField(DSL.name("ZVENDOR"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.BUKRS</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> BUKRS = createField(DSL.name("BUKRS"), SQLDataType.VARCHAR(4), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZCUSTOMER</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZCUSTOMER = createField(DSL.name("ZCUSTOMER"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.WERKS</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> WERKS = createField(DSL.name("WERKS"), SQLDataType.VARCHAR(4), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZSDATE</code>.
     */
    public final TableField<HmbServiceDeductionRecord, LocalDate> ZSDATE = createField(DSL.name("ZSDATE"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZCC_HMB</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZCC_HMB = createField(DSL.name("ZCC_HMB"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZBILLCYCLE</code>.
     */
    public final TableField<HmbServiceDeductionRecord, Integer> ZBILLCYCLE = createField(DSL.name("ZBILLCYCLE"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZAMOUNT</code>.
     */
    public final TableField<HmbServiceDeductionRecord, BigDecimal> ZAMOUNT = createField(DSL.name("ZAMOUNT"), SQLDataType.DECIMAL(13, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZEMIAMT</code>.
     */
    public final TableField<HmbServiceDeductionRecord, BigDecimal> ZEMIAMT = createField(DSL.name("ZEMIAMT"), SQLDataType.DECIMAL(13, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.P_AMT</code>.
     */
    public final TableField<HmbServiceDeductionRecord, BigDecimal> P_AMT = createField(DSL.name("P_AMT"), SQLDataType.DECIMAL(13, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZDEDAMT</code>.
     */
    public final TableField<HmbServiceDeductionRecord, BigDecimal> ZDEDAMT = createField(DSL.name("ZDEDAMT"), SQLDataType.DECIMAL(13, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.S_AMT</code>.
     */
    public final TableField<HmbServiceDeductionRecord, BigDecimal> S_AMT = createField(DSL.name("S_AMT"), SQLDataType.DECIMAL(13, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZBALANCE</code>.
     */
    public final TableField<HmbServiceDeductionRecord, BigDecimal> ZBALANCE = createField(DSL.name("ZBALANCE"), SQLDataType.DECIMAL(13, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZLOANAC</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZLOANAC = createField(DSL.name("ZLOANAC"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZBANKEY</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZBANKEY = createField(DSL.name("ZBANKEY"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.SAKNR</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> SAKNR = createField(DSL.name("SAKNR"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZDEDDOC</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZDEDDOC = createField(DSL.name("ZDEDDOC"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZPRSTA</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZPRSTA = createField(DSL.name("ZPRSTA"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZAPPSTA</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZAPPSTA = createField(DSL.name("ZAPPSTA"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZAPPRBY</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZAPPRBY = createField(DSL.name("ZAPPRBY"), SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZAPPDATE</code>.
     */
    public final TableField<HmbServiceDeductionRecord, LocalDate> ZAPPDATE = createField(DSL.name("ZAPPDATE"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZREJBY</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZREJBY = createField(DSL.name("ZREJBY"), SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZREJDATE</code>.
     */
    public final TableField<HmbServiceDeductionRecord, LocalDate> ZREJDATE = createField(DSL.name("ZREJDATE"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZDELFG</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZDELFG = createField(DSL.name("ZDELFG"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZDELBY</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZDELBY = createField(DSL.name("ZDELBY"), SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZDELDATE</code>.
     */
    public final TableField<HmbServiceDeductionRecord, LocalDate> ZDELDATE = createField(DSL.name("ZDELDATE"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZREMARK1</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZREMARK1 = createField(DSL.name("ZREMARK1"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZREMARK2</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZREMARK2 = createField(DSL.name("ZREMARK2"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ZWERKS</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ZWERKS = createField(DSL.name("ZWERKS"), SQLDataType.VARCHAR(4), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.ROUTE_NO</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> ROUTE_NO = createField(DSL.name("ROUTE_NO"), SQLDataType.VARCHAR(6), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.TRUCK_NO</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> TRUCK_NO = createField(DSL.name("TRUCK_NO"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.PAID</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> PAID = createField(DSL.name("PAID"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.BILL_NUM</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> BILL_NUM = createField(DSL.name("BILL_NUM"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.QUANTITY</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> QUANTITY = createField(DSL.name("QUANTITY"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.UOM</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> UOM = createField(DSL.name("UOM"), SQLDataType.VARCHAR(5), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.STATUS</code>.
     */
    public final TableField<HmbServiceDeductionRecord, String> STATUS = createField(DSL.name("STATUS"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.CREATED_BY</code>.
     */
    public final TableField<HmbServiceDeductionRecord, Integer> CREATED_BY = createField(DSL.name("CREATED_BY"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.CREATED_ON</code>.
     */
    public final TableField<HmbServiceDeductionRecord, LocalDateTime> CREATED_ON = createField(DSL.name("CREATED_ON"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.LAST_CHANGED_BY</code>.
     */
    public final TableField<HmbServiceDeductionRecord, Integer> LAST_CHANGED_BY = createField(DSL.name("LAST_CHANGED_BY"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>vendor_portal_pbx.hmb_service_deduction.LAST_CHANGED_ON</code>.
     */
    public final TableField<HmbServiceDeductionRecord, LocalDateTime> LAST_CHANGED_ON = createField(DSL.name("LAST_CHANGED_ON"), SQLDataType.LOCALDATETIME(0), this, "");

    private HmbServiceDeduction(Name alias, Table<HmbServiceDeductionRecord> aliased) {
        this(alias, aliased, null);
    }

    private HmbServiceDeduction(Name alias, Table<HmbServiceDeductionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.hmb_service_deduction</code> table reference
     */
    public HmbServiceDeduction(String alias) {
        this(DSL.name(alias), HMB_SERVICE_DEDUCTION);
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.hmb_service_deduction</code> table reference
     */
    public HmbServiceDeduction(Name alias) {
        this(alias, HMB_SERVICE_DEDUCTION);
    }

    /**
     * Create a <code>vendor_portal_pbx.hmb_service_deduction</code> table reference
     */
    public HmbServiceDeduction() {
        this(DSL.name("hmb_service_deduction"), null);
    }

    public <O extends Record> HmbServiceDeduction(Table<O> child, ForeignKey<O, HmbServiceDeductionRecord> key) {
        super(child, key, HMB_SERVICE_DEDUCTION);
    }

    @Override
    public Schema getSchema() {
        return VendorPortalPbx.VENDOR_PORTAL_PBX;
    }

    @Override
    public UniqueKey<HmbServiceDeductionRecord> getPrimaryKey() {
        return Keys.KEY_HMB_SERVICE_DEDUCTION_PRIMARY;
    }

    @Override
    public List<UniqueKey<HmbServiceDeductionRecord>> getKeys() {
        return Arrays.<UniqueKey<HmbServiceDeductionRecord>>asList(Keys.KEY_HMB_SERVICE_DEDUCTION_PRIMARY);
    }

    @Override
    public HmbServiceDeduction as(String alias) {
        return new HmbServiceDeduction(DSL.name(alias), this);
    }

    @Override
    public HmbServiceDeduction as(Name alias) {
        return new HmbServiceDeduction(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public HmbServiceDeduction rename(String name) {
        return new HmbServiceDeduction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HmbServiceDeduction rename(Name name) {
        return new HmbServiceDeduction(name, null);
    }
}
