/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables;


import com.jooq.jooq.model.Keys;
import com.jooq.jooq.model.VendorPortalPbx;
import com.jooq.jooq.model.tables.records.RentHaRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RentHa extends TableImpl<RentHaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>vendor_portal_pbx.rent_ha</code>
     */
    public static final RentHa RENT_HA = new RentHa();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RentHaRecord> getRecordType() {
        return RentHaRecord.class;
    }

    /**
     * The column <code>vendor_portal_pbx.rent_ha.COMP_CODE</code>.
     */
    public final TableField<RentHaRecord, String> COMP_CODE = createField(DSL.name("COMP_CODE"), SQLDataType.VARCHAR(4).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.RENT_AGR_ID</code>.
     */
    public final TableField<RentHaRecord, String> RENT_AGR_ID = createField(DSL.name("RENT_AGR_ID"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.RENT_AGR_NAME</code>.
     */
    public final TableField<RentHaRecord, String> RENT_AGR_NAME = createField(DSL.name("RENT_AGR_NAME"), SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.AGR_TYPE</code>.
     */
    public final TableField<RentHaRecord, String> AGR_TYPE = createField(DSL.name("AGR_TYPE"), SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.AGR_ST_DAT</code>.
     */
    public final TableField<RentHaRecord, LocalDate> AGR_ST_DAT = createField(DSL.name("AGR_ST_DAT"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.AGR_EN_DAT</code>.
     */
    public final TableField<RentHaRecord, LocalDate> AGR_EN_DAT = createField(DSL.name("AGR_EN_DAT"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.AGR_SIGN_DAT</code>.
     */
    public final TableField<RentHaRecord, LocalDate> AGR_SIGN_DAT = createField(DSL.name("AGR_SIGN_DAT"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.BUSI_TYPE</code>.
     */
    public final TableField<RentHaRecord, String> BUSI_TYPE = createField(DSL.name("BUSI_TYPE"), SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.REG_IND</code>.
     */
    public final TableField<RentHaRecord, String> REG_IND = createField(DSL.name("REG_IND"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.SHORT_CLOSE</code>.
     */
    public final TableField<RentHaRecord, String> SHORT_CLOSE = createField(DSL.name("SHORT_CLOSE"), SQLDataType.VARCHAR(8), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.BUILDING</code>.
     */
    public final TableField<RentHaRecord, String> BUILDING = createField(DSL.name("BUILDING"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.FLOOR</code>.
     */
    public final TableField<RentHaRecord, String> FLOOR = createField(DSL.name("FLOOR"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.ROOM_NUMBER</code>.
     */
    public final TableField<RentHaRecord, String> ROOM_NUMBER = createField(DSL.name("ROOM_NUMBER"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.HOUSE_NUM1</code>.
     */
    public final TableField<RentHaRecord, String> HOUSE_NUM1 = createField(DSL.name("HOUSE_NUM1"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.STREET1</code>.
     */
    public final TableField<RentHaRecord, String> STREET1 = createField(DSL.name("STREET1"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.STREET2</code>.
     */
    public final TableField<RentHaRecord, String> STREET2 = createField(DSL.name("STREET2"), SQLDataType.VARCHAR(60), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.POST_CODE1</code>.
     */
    public final TableField<RentHaRecord, String> POST_CODE1 = createField(DSL.name("POST_CODE1"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.CITY1</code>.
     */
    public final TableField<RentHaRecord, String> CITY1 = createField(DSL.name("CITY1"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.COUNTRY</code>.
     */
    public final TableField<RentHaRecord, String> COUNTRY = createField(DSL.name("COUNTRY"), SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.BLAND</code>.
     */
    public final TableField<RentHaRecord, String> BLAND = createField(DSL.name("BLAND"), SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.LATTITUDE_D</code>.
     */
    public final TableField<RentHaRecord, String> LATTITUDE_D = createField(DSL.name("LATTITUDE_D"), SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.LATTITUDE_T</code>.
     */
    public final TableField<RentHaRecord, String> LATTITUDE_T = createField(DSL.name("LATTITUDE_T"), SQLDataType.VARCHAR(6), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.LATTITUDE_DTR</code>.
     */
    public final TableField<RentHaRecord, String> LATTITUDE_DTR = createField(DSL.name("LATTITUDE_DTR"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.LONGITUDE_D</code>.
     */
    public final TableField<RentHaRecord, String> LONGITUDE_D = createField(DSL.name("LONGITUDE_D"), SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.LONGITUDE_T</code>.
     */
    public final TableField<RentHaRecord, String> LONGITUDE_T = createField(DSL.name("LONGITUDE_T"), SQLDataType.VARCHAR(6), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.LONGITUDE_DIR</code>.
     */
    public final TableField<RentHaRecord, String> LONGITUDE_DIR = createField(DSL.name("LONGITUDE_DIR"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.PROPERTY_ID</code>.
     */
    public final TableField<RentHaRecord, String> PROPERTY_ID = createField(DSL.name("PROPERTY_ID"), SQLDataType.VARCHAR(9), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.CATEGORY_ID</code>.
     */
    public final TableField<RentHaRecord, String> CATEGORY_ID = createField(DSL.name("CATEGORY_ID"), SQLDataType.VARCHAR(9), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.SAKNR</code>.
     */
    public final TableField<RentHaRecord, String> SAKNR = createField(DSL.name("SAKNR"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.KOSTL</code>.
     */
    public final TableField<RentHaRecord, String> KOSTL = createField(DSL.name("KOSTL"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.KOSTL2</code>.
     */
    public final TableField<RentHaRecord, String> KOSTL2 = createField(DSL.name("KOSTL2"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.INT_RBASE_AMT</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> INT_RBASE_AMT = createField(DSL.name("INT_RBASE_AMT"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.BASE_AMT</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> BASE_AMT = createField(DSL.name("BASE_AMT"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.ADV_AMT</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> ADV_AMT = createField(DSL.name("ADV_AMT"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.ADV_DATE</code>.
     */
    public final TableField<RentHaRecord, LocalDate> ADV_DATE = createField(DSL.name("ADV_DATE"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.UOM</code>.
     */
    public final TableField<RentHaRecord, String> UOM = createField(DSL.name("UOM"), SQLDataType.VARCHAR(5), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.R_INCREMENT</code>.
     */
    public final TableField<RentHaRecord, String> R_INCREMENT = createField(DSL.name("R_INCREMENT"), SQLDataType.VARCHAR(4), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.MWSKZ</code>.
     */
    public final TableField<RentHaRecord, String> MWSKZ = createField(DSL.name("MWSKZ"), SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.RENT_AGR_NAME_UP</code>.
     */
    public final TableField<RentHaRecord, String> RENT_AGR_NAME_UP = createField(DSL.name("RENT_AGR_NAME_UP"), SQLDataType.VARCHAR(80), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.ORIGINAL_AGR_ID</code>.
     */
    public final TableField<RentHaRecord, String> ORIGINAL_AGR_ID = createField(DSL.name("ORIGINAL_AGR_ID"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.RENEW_REF_AGR_ID</code>.
     */
    public final TableField<RentHaRecord, String> RENEW_REF_AGR_ID = createField(DSL.name("RENEW_REF_AGR_ID"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.ORG_BASE_AMT</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> ORG_BASE_AMT = createField(DSL.name("ORG_BASE_AMT"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.REV_ORG_BASE_AMT</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> REV_ORG_BASE_AMT = createField(DSL.name("REV_ORG_BASE_AMT"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.PREV_REN_AMT</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> PREV_REN_AMT = createField(DSL.name("PREV_REN_AMT"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.PREV_BASE_AMT</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> PREV_BASE_AMT = createField(DSL.name("PREV_BASE_AMT"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.CURR_REN_AMT</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> CURR_REN_AMT = createField(DSL.name("CURR_REN_AMT"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.ORG_ADV_AMT</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> ORG_ADV_AMT = createField(DSL.name("ORG_ADV_AMT"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.PREV_ADV_AMT</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> PREV_ADV_AMT = createField(DSL.name("PREV_ADV_AMT"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.CURR_ADV_AMT</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> CURR_ADV_AMT = createField(DSL.name("CURR_ADV_AMT"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.AGR_IND</code>.
     */
    public final TableField<RentHaRecord, String> AGR_IND = createField(DSL.name("AGR_IND"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.ADDEN_AMT</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> ADDEN_AMT = createField(DSL.name("ADDEN_AMT"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.ADDEN_FLG</code>.
     */
    public final TableField<RentHaRecord, String> ADDEN_FLG = createField(DSL.name("ADDEN_FLG"), SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.REV_BASE_AMT</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> REV_BASE_AMT = createField(DSL.name("REV_BASE_AMT"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.TOT_INC_AMT</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> TOT_INC_AMT = createField(DSL.name("TOT_INC_AMT"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.SH_CL_REM</code>.
     */
    public final TableField<RentHaRecord, String> SH_CL_REM = createField(DSL.name("SH_CL_REM"), SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.TOT_RENT_INC</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> TOT_RENT_INC = createField(DSL.name("TOT_RENT_INC"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.TOT_MAIN_INC</code>.
     */
    public final TableField<RentHaRecord, BigDecimal> TOT_MAIN_INC = createField(DSL.name("TOT_MAIN_INC"), SQLDataType.DECIMAL(16, 2), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.BUSINESS_PLACE</code>.
     */
    public final TableField<RentHaRecord, String> BUSINESS_PLACE = createField(DSL.name("BUSINESS_PLACE"), SQLDataType.VARCHAR(4), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.COST_CEN_SQFT1</code>.
     */
    public final TableField<RentHaRecord, String> COST_CEN_SQFT1 = createField(DSL.name("COST_CEN_SQFT1"), SQLDataType.VARCHAR(5), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.COST_CEN_SQFT2</code>.
     */
    public final TableField<RentHaRecord, String> COST_CEN_SQFT2 = createField(DSL.name("COST_CEN_SQFT2"), SQLDataType.VARCHAR(5), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.HATSUN_AGREEMENT</code>.
     */
    public final TableField<RentHaRecord, String> HATSUN_AGREEMENT = createField(DSL.name("HATSUN_AGREEMENT"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.VENDOR_AGREEMANT</code>.
     */
    public final TableField<RentHaRecord, String> VENDOR_AGREEMANT = createField(DSL.name("VENDOR_AGREEMANT"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.ERNAM</code>.
     */
    public final TableField<RentHaRecord, String> ERNAM = createField(DSL.name("ERNAM"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.ERSDA</code>.
     */
    public final TableField<RentHaRecord, LocalDate> ERSDA = createField(DSL.name("ERSDA"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.CRTIM</code>.
     */
    public final TableField<RentHaRecord, LocalTime> CRTIM = createField(DSL.name("CRTIM"), SQLDataType.LOCALTIME, this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.AENAM</code>.
     */
    public final TableField<RentHaRecord, String> AENAM = createField(DSL.name("AENAM"), SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.LAEDA</code>.
     */
    public final TableField<RentHaRecord, LocalDate> LAEDA = createField(DSL.name("LAEDA"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>vendor_portal_pbx.rent_ha.CHTIM</code>.
     */
    public final TableField<RentHaRecord, LocalTime> CHTIM = createField(DSL.name("CHTIM"), SQLDataType.LOCALTIME, this, "");

    private RentHa(Name alias, Table<RentHaRecord> aliased) {
        this(alias, aliased, null);
    }

    private RentHa(Name alias, Table<RentHaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.rent_ha</code> table reference
     */
    public RentHa(String alias) {
        this(DSL.name(alias), RENT_HA);
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.rent_ha</code> table reference
     */
    public RentHa(Name alias) {
        this(alias, RENT_HA);
    }

    /**
     * Create a <code>vendor_portal_pbx.rent_ha</code> table reference
     */
    public RentHa() {
        this(DSL.name("rent_ha"), null);
    }

    public <O extends Record> RentHa(Table<O> child, ForeignKey<O, RentHaRecord> key) {
        super(child, key, RENT_HA);
    }

    @Override
    public Schema getSchema() {
        return VendorPortalPbx.VENDOR_PORTAL_PBX;
    }

    @Override
    public UniqueKey<RentHaRecord> getPrimaryKey() {
        return Keys.KEY_RENT_HA_PRIMARY;
    }

    @Override
    public List<UniqueKey<RentHaRecord>> getKeys() {
        return Arrays.<UniqueKey<RentHaRecord>>asList(Keys.KEY_RENT_HA_PRIMARY);
    }

    @Override
    public RentHa as(String alias) {
        return new RentHa(DSL.name(alias), this);
    }

    @Override
    public RentHa as(Name alias) {
        return new RentHa(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RentHa rename(String name) {
        return new RentHa(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RentHa rename(Name name) {
        return new RentHa(name, null);
    }
}
