/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables;


import com.jooq.jooq.model.Indexes;
import com.jooq.jooq.model.Keys;
import com.jooq.jooq.model.VendorPortalPbx;
import com.jooq.jooq.model.tables.records.TcUserTrainingCenterMasterRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TcUserTrainingCenterMaster extends TableImpl<TcUserTrainingCenterMasterRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER</code>
     */
    public static final TcUserTrainingCenterMaster TC_USER_TRAINING_CENTER_MASTER = new TcUserTrainingCenterMaster();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TcUserTrainingCenterMasterRecord> getRecordType() {
        return TcUserTrainingCenterMasterRecord.class;
    }

    /**
     * The column <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER.USER_ID</code>.
     */
    public final TableField<TcUserTrainingCenterMasterRecord, String> USER_ID = createField(DSL.name("USER_ID"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER.TR_CENTER_CODE</code>.
     */
    public final TableField<TcUserTrainingCenterMasterRecord, Integer> TR_CENTER_CODE = createField(DSL.name("TR_CENTER_CODE"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER.FROM_DATE</code>.
     */
    public final TableField<TcUserTrainingCenterMasterRecord, LocalDate> FROM_DATE = createField(DSL.name("FROM_DATE"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER.TO_DATE</code>.
     */
    public final TableField<TcUserTrainingCenterMasterRecord, LocalDate> TO_DATE = createField(DSL.name("TO_DATE"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER.STATUS</code>.
     */
    public final TableField<TcUserTrainingCenterMasterRecord, String> STATUS = createField(DSL.name("STATUS"), SQLDataType.VARCHAR(1), this, "");

    private TcUserTrainingCenterMaster(Name alias, Table<TcUserTrainingCenterMasterRecord> aliased) {
        this(alias, aliased, null);
    }

    private TcUserTrainingCenterMaster(Name alias, Table<TcUserTrainingCenterMasterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER</code> table reference
     */
    public TcUserTrainingCenterMaster(String alias) {
        this(DSL.name(alias), TC_USER_TRAINING_CENTER_MASTER);
    }

    /**
     * Create an aliased <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER</code> table reference
     */
    public TcUserTrainingCenterMaster(Name alias) {
        this(alias, TC_USER_TRAINING_CENTER_MASTER);
    }

    /**
     * Create a <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER</code> table reference
     */
    public TcUserTrainingCenterMaster() {
        this(DSL.name("TC_USER_TRAINING_CENTER_MASTER"), null);
    }

    public <O extends Record> TcUserTrainingCenterMaster(Table<O> child, ForeignKey<O, TcUserTrainingCenterMasterRecord> key) {
        super(child, key, TC_USER_TRAINING_CENTER_MASTER);
    }

    @Override
    public Schema getSchema() {
        return VendorPortalPbx.VENDOR_PORTAL_PBX;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TC_USER_TRAINING_CENTER_MASTER_FK_USER_TRAINING_CODE_IDX);
    }

    @Override
    public UniqueKey<TcUserTrainingCenterMasterRecord> getPrimaryKey() {
        return Keys.KEY_TC_USER_TRAINING_CENTER_MASTER_PRIMARY;
    }

    @Override
    public List<UniqueKey<TcUserTrainingCenterMasterRecord>> getKeys() {
        return Arrays.<UniqueKey<TcUserTrainingCenterMasterRecord>>asList(Keys.KEY_TC_USER_TRAINING_CENTER_MASTER_PRIMARY);
    }

    @Override
    public List<ForeignKey<TcUserTrainingCenterMasterRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TcUserTrainingCenterMasterRecord, ?>>asList(Keys.FK_USER_TRAINING_CODE);
    }

    private transient TcTrainingCenter _tcTrainingCenter;

    public TcTrainingCenter tcTrainingCenter() {
        if (_tcTrainingCenter == null)
            _tcTrainingCenter = new TcTrainingCenter(this, Keys.FK_USER_TRAINING_CODE);

        return _tcTrainingCenter;
    }

    @Override
    public TcUserTrainingCenterMaster as(String alias) {
        return new TcUserTrainingCenterMaster(DSL.name(alias), this);
    }

    @Override
    public TcUserTrainingCenterMaster as(Name alias) {
        return new TcUserTrainingCenterMaster(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TcUserTrainingCenterMaster rename(String name) {
        return new TcUserTrainingCenterMaster(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TcUserTrainingCenterMaster rename(Name name) {
        return new TcUserTrainingCenterMaster(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, Integer, LocalDate, LocalDate, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
