/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.records;


import com.jooq.jooq.model.tables.BpCustomer;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BpCustomerRecord extends UpdatableRecordImpl<BpCustomerRecord> implements Record5<Integer, String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor_portal_pbx.bp_customer.id</code>.
     */
    public BpCustomerRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.bp_customer.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vendor_portal_pbx.bp_customer.customer_name</code>.
     */
    public BpCustomerRecord setCustomerName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.bp_customer.customer_name</code>.
     */
    public String getCustomerName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vendor_portal_pbx.bp_customer.customer_code</code>.
     */
    public BpCustomerRecord setCustomerCode(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.bp_customer.customer_code</code>.
     */
    public String getCustomerCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vendor_portal_pbx.bp_customer.mobile</code>.
     */
    public BpCustomerRecord setMobile(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.bp_customer.mobile</code>.
     */
    public String getMobile() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vendor_portal_pbx.bp_customer.product_id</code>.
     */
    public BpCustomerRecord setProductId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.bp_customer.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return BpCustomer.BP_CUSTOMER.ID;
    }

    @Override
    public Field<String> field2() {
        return BpCustomer.BP_CUSTOMER.CUSTOMER_NAME;
    }

    @Override
    public Field<String> field3() {
        return BpCustomer.BP_CUSTOMER.CUSTOMER_CODE;
    }

    @Override
    public Field<String> field4() {
        return BpCustomer.BP_CUSTOMER.MOBILE;
    }

    @Override
    public Field<Integer> field5() {
        return BpCustomer.BP_CUSTOMER.PRODUCT_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCustomerName();
    }

    @Override
    public String component3() {
        return getCustomerCode();
    }

    @Override
    public String component4() {
        return getMobile();
    }

    @Override
    public Integer component5() {
        return getProductId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCustomerName();
    }

    @Override
    public String value3() {
        return getCustomerCode();
    }

    @Override
    public String value4() {
        return getMobile();
    }

    @Override
    public Integer value5() {
        return getProductId();
    }

    @Override
    public BpCustomerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public BpCustomerRecord value2(String value) {
        setCustomerName(value);
        return this;
    }

    @Override
    public BpCustomerRecord value3(String value) {
        setCustomerCode(value);
        return this;
    }

    @Override
    public BpCustomerRecord value4(String value) {
        setMobile(value);
        return this;
    }

    @Override
    public BpCustomerRecord value5(Integer value) {
        setProductId(value);
        return this;
    }

    @Override
    public BpCustomerRecord values(Integer value1, String value2, String value3, String value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BpCustomerRecord
     */
    public BpCustomerRecord() {
        super(BpCustomer.BP_CUSTOMER);
    }

    /**
     * Create a detached, initialised BpCustomerRecord
     */
    public BpCustomerRecord(Integer id, String customerName, String customerCode, String mobile, Integer productId) {
        super(BpCustomer.BP_CUSTOMER);

        setId(id);
        setCustomerName(customerName);
        setCustomerCode(customerCode);
        setMobile(mobile);
        setProductId(productId);
    }
}
