/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.records;


import com.jooq.jooq.model.tables.CcmsVendorPlantMapping;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CcmsVendorPlantMappingRecord extends UpdatableRecordImpl<CcmsVendorPlantMappingRecord> implements Record8<String, String, Integer, String, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.vendor_code</code>.
     */
    public CcmsVendorPlantMappingRecord setVendorCode(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.vendor_code</code>.
     */
    public String getVendorCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.plant</code>.
     */
    public CcmsVendorPlantMappingRecord setPlant(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.plant</code>.
     */
    public String getPlant() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.num_range</code>.
     */
    public CcmsVendorPlantMappingRecord setNumRange(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.num_range</code>.
     */
    public Integer getNumRange() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.status</code>.
     */
    public CcmsVendorPlantMappingRecord setStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.created_by</code>.
     */
    public CcmsVendorPlantMappingRecord setCreatedBy(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.created_on</code>.
     */
    public CcmsVendorPlantMappingRecord setCreatedOn(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.last_changed_by</code>.
     */
    public CcmsVendorPlantMappingRecord setLastChangedBy(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.last_changed_by</code>.
     */
    public String getLastChangedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.last_changed_on</code>.
     */
    public CcmsVendorPlantMappingRecord setLastChangedOn(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ccms_vendor_plant_mapping.last_changed_on</code>.
     */
    public LocalDateTime getLastChangedOn() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<String, String, Integer, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<String, String, Integer, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return CcmsVendorPlantMapping.CCMS_VENDOR_PLANT_MAPPING.VENDOR_CODE;
    }

    @Override
    public Field<String> field2() {
        return CcmsVendorPlantMapping.CCMS_VENDOR_PLANT_MAPPING.PLANT;
    }

    @Override
    public Field<Integer> field3() {
        return CcmsVendorPlantMapping.CCMS_VENDOR_PLANT_MAPPING.NUM_RANGE;
    }

    @Override
    public Field<String> field4() {
        return CcmsVendorPlantMapping.CCMS_VENDOR_PLANT_MAPPING.STATUS;
    }

    @Override
    public Field<String> field5() {
        return CcmsVendorPlantMapping.CCMS_VENDOR_PLANT_MAPPING.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return CcmsVendorPlantMapping.CCMS_VENDOR_PLANT_MAPPING.CREATED_ON;
    }

    @Override
    public Field<String> field7() {
        return CcmsVendorPlantMapping.CCMS_VENDOR_PLANT_MAPPING.LAST_CHANGED_BY;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return CcmsVendorPlantMapping.CCMS_VENDOR_PLANT_MAPPING.LAST_CHANGED_ON;
    }

    @Override
    public String component1() {
        return getVendorCode();
    }

    @Override
    public String component2() {
        return getPlant();
    }

    @Override
    public Integer component3() {
        return getNumRange();
    }

    @Override
    public String component4() {
        return getStatus();
    }

    @Override
    public String component5() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedOn();
    }

    @Override
    public String component7() {
        return getLastChangedBy();
    }

    @Override
    public LocalDateTime component8() {
        return getLastChangedOn();
    }

    @Override
    public String value1() {
        return getVendorCode();
    }

    @Override
    public String value2() {
        return getPlant();
    }

    @Override
    public Integer value3() {
        return getNumRange();
    }

    @Override
    public String value4() {
        return getStatus();
    }

    @Override
    public String value5() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedOn();
    }

    @Override
    public String value7() {
        return getLastChangedBy();
    }

    @Override
    public LocalDateTime value8() {
        return getLastChangedOn();
    }

    @Override
    public CcmsVendorPlantMappingRecord value1(String value) {
        setVendorCode(value);
        return this;
    }

    @Override
    public CcmsVendorPlantMappingRecord value2(String value) {
        setPlant(value);
        return this;
    }

    @Override
    public CcmsVendorPlantMappingRecord value3(Integer value) {
        setNumRange(value);
        return this;
    }

    @Override
    public CcmsVendorPlantMappingRecord value4(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public CcmsVendorPlantMappingRecord value5(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public CcmsVendorPlantMappingRecord value6(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public CcmsVendorPlantMappingRecord value7(String value) {
        setLastChangedBy(value);
        return this;
    }

    @Override
    public CcmsVendorPlantMappingRecord value8(LocalDateTime value) {
        setLastChangedOn(value);
        return this;
    }

    @Override
    public CcmsVendorPlantMappingRecord values(String value1, String value2, Integer value3, String value4, String value5, LocalDateTime value6, String value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CcmsVendorPlantMappingRecord
     */
    public CcmsVendorPlantMappingRecord() {
        super(CcmsVendorPlantMapping.CCMS_VENDOR_PLANT_MAPPING);
    }

    /**
     * Create a detached, initialised CcmsVendorPlantMappingRecord
     */
    public CcmsVendorPlantMappingRecord(String vendorCode, String plant, Integer numRange, String status, String createdBy, LocalDateTime createdOn, String lastChangedBy, LocalDateTime lastChangedOn) {
        super(CcmsVendorPlantMapping.CCMS_VENDOR_PLANT_MAPPING);

        setVendorCode(vendorCode);
        setPlant(plant);
        setNumRange(numRange);
        setStatus(status);
        setCreatedBy(createdBy);
        setCreatedOn(createdOn);
        setLastChangedBy(lastChangedBy);
        setLastChangedOn(lastChangedOn);
    }
}
