/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.records;


import com.jooq.jooq.model.tables.CfaSlabMaster;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CfaSlabMasterRecord extends UpdatableRecordImpl<CfaSlabMasterRecord> implements Record7<Integer, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor_portal_pbx.cfa_slab_master.SNO</code>.
     */
    public CfaSlabMasterRecord setSno(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.cfa_slab_master.SNO</code>.
     */
    public Integer getSno() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vendor_portal_pbx.cfa_slab_master.SLAB</code>.
     */
    public CfaSlabMasterRecord setSlab(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.cfa_slab_master.SLAB</code>.
     */
    public String getSlab() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vendor_portal_pbx.cfa_slab_master.KM</code>.
     */
    public CfaSlabMasterRecord setKm(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.cfa_slab_master.KM</code>.
     */
    public String getKm() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vendor_portal_pbx.cfa_slab_master.RATE_PER_KM</code>.
     */
    public CfaSlabMasterRecord setRatePerKm(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.cfa_slab_master.RATE_PER_KM</code>.
     */
    public String getRatePerKm() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vendor_portal_pbx.cfa_slab_master.STATUS</code>.
     */
    public CfaSlabMasterRecord setStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.cfa_slab_master.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vendor_portal_pbx.cfa_slab_master.SLAB_NAME</code>.
     */
    public CfaSlabMasterRecord setSlabName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.cfa_slab_master.SLAB_NAME</code>.
     */
    public String getSlabName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>vendor_portal_pbx.cfa_slab_master.REGION</code>.
     */
    public CfaSlabMasterRecord setRegion(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.cfa_slab_master.REGION</code>.
     */
    public String getRegion() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return CfaSlabMaster.CFA_SLAB_MASTER.SNO;
    }

    @Override
    public Field<String> field2() {
        return CfaSlabMaster.CFA_SLAB_MASTER.SLAB;
    }

    @Override
    public Field<String> field3() {
        return CfaSlabMaster.CFA_SLAB_MASTER.KM;
    }

    @Override
    public Field<String> field4() {
        return CfaSlabMaster.CFA_SLAB_MASTER.RATE_PER_KM;
    }

    @Override
    public Field<String> field5() {
        return CfaSlabMaster.CFA_SLAB_MASTER.STATUS;
    }

    @Override
    public Field<String> field6() {
        return CfaSlabMaster.CFA_SLAB_MASTER.SLAB_NAME;
    }

    @Override
    public Field<String> field7() {
        return CfaSlabMaster.CFA_SLAB_MASTER.REGION;
    }

    @Override
    public Integer component1() {
        return getSno();
    }

    @Override
    public String component2() {
        return getSlab();
    }

    @Override
    public String component3() {
        return getKm();
    }

    @Override
    public String component4() {
        return getRatePerKm();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public String component6() {
        return getSlabName();
    }

    @Override
    public String component7() {
        return getRegion();
    }

    @Override
    public Integer value1() {
        return getSno();
    }

    @Override
    public String value2() {
        return getSlab();
    }

    @Override
    public String value3() {
        return getKm();
    }

    @Override
    public String value4() {
        return getRatePerKm();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public String value6() {
        return getSlabName();
    }

    @Override
    public String value7() {
        return getRegion();
    }

    @Override
    public CfaSlabMasterRecord value1(Integer value) {
        setSno(value);
        return this;
    }

    @Override
    public CfaSlabMasterRecord value2(String value) {
        setSlab(value);
        return this;
    }

    @Override
    public CfaSlabMasterRecord value3(String value) {
        setKm(value);
        return this;
    }

    @Override
    public CfaSlabMasterRecord value4(String value) {
        setRatePerKm(value);
        return this;
    }

    @Override
    public CfaSlabMasterRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public CfaSlabMasterRecord value6(String value) {
        setSlabName(value);
        return this;
    }

    @Override
    public CfaSlabMasterRecord value7(String value) {
        setRegion(value);
        return this;
    }

    @Override
    public CfaSlabMasterRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CfaSlabMasterRecord
     */
    public CfaSlabMasterRecord() {
        super(CfaSlabMaster.CFA_SLAB_MASTER);
    }

    /**
     * Create a detached, initialised CfaSlabMasterRecord
     */
    public CfaSlabMasterRecord(Integer sno, String slab, String km, String ratePerKm, String status, String slabName, String region) {
        super(CfaSlabMaster.CFA_SLAB_MASTER);

        setSno(sno);
        setSlab(slab);
        setKm(km);
        setRatePerKm(ratePerKm);
        setStatus(status);
        setSlabName(slabName);
        setRegion(region);
    }
}
