/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.records;


import com.jooq.jooq.model.tables.FieldForceStaffHmb;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FieldForceStaffHmbRecord extends UpdatableRecordImpl<FieldForceStaffHmbRecord> implements Record5<String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor_portal_pbx.field_force_staff_hmb.PLANT_CODE</code>.
     */
    public FieldForceStaffHmbRecord setPlantCode(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.field_force_staff_hmb.PLANT_CODE</code>.
     */
    public String getPlantCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>vendor_portal_pbx.field_force_staff_hmb.HMB</code>.
     */
    public FieldForceStaffHmbRecord setHmb(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.field_force_staff_hmb.HMB</code>.
     */
    public String getHmb() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vendor_portal_pbx.field_force_staff_hmb.VENDOR</code>.
     */
    public FieldForceStaffHmbRecord setVendor(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.field_force_staff_hmb.VENDOR</code>.
     */
    public String getVendor() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vendor_portal_pbx.field_force_staff_hmb.HMB_NAME</code>.
     */
    public FieldForceStaffHmbRecord setHmbName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.field_force_staff_hmb.HMB_NAME</code>.
     */
    public String getHmbName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vendor_portal_pbx.field_force_staff_hmb.STATUS</code>.
     */
    public FieldForceStaffHmbRecord setStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.field_force_staff_hmb.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record4<String, String, String, String> key() {
        return (Record4) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return FieldForceStaffHmb.FIELD_FORCE_STAFF_HMB.PLANT_CODE;
    }

    @Override
    public Field<String> field2() {
        return FieldForceStaffHmb.FIELD_FORCE_STAFF_HMB.HMB;
    }

    @Override
    public Field<String> field3() {
        return FieldForceStaffHmb.FIELD_FORCE_STAFF_HMB.VENDOR;
    }

    @Override
    public Field<String> field4() {
        return FieldForceStaffHmb.FIELD_FORCE_STAFF_HMB.HMB_NAME;
    }

    @Override
    public Field<String> field5() {
        return FieldForceStaffHmb.FIELD_FORCE_STAFF_HMB.STATUS;
    }

    @Override
    public String component1() {
        return getPlantCode();
    }

    @Override
    public String component2() {
        return getHmb();
    }

    @Override
    public String component3() {
        return getVendor();
    }

    @Override
    public String component4() {
        return getHmbName();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public String value1() {
        return getPlantCode();
    }

    @Override
    public String value2() {
        return getHmb();
    }

    @Override
    public String value3() {
        return getVendor();
    }

    @Override
    public String value4() {
        return getHmbName();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public FieldForceStaffHmbRecord value1(String value) {
        setPlantCode(value);
        return this;
    }

    @Override
    public FieldForceStaffHmbRecord value2(String value) {
        setHmb(value);
        return this;
    }

    @Override
    public FieldForceStaffHmbRecord value3(String value) {
        setVendor(value);
        return this;
    }

    @Override
    public FieldForceStaffHmbRecord value4(String value) {
        setHmbName(value);
        return this;
    }

    @Override
    public FieldForceStaffHmbRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public FieldForceStaffHmbRecord values(String value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FieldForceStaffHmbRecord
     */
    public FieldForceStaffHmbRecord() {
        super(FieldForceStaffHmb.FIELD_FORCE_STAFF_HMB);
    }

    /**
     * Create a detached, initialised FieldForceStaffHmbRecord
     */
    public FieldForceStaffHmbRecord(String plantCode, String hmb, String vendor, String hmbName, String status) {
        super(FieldForceStaffHmb.FIELD_FORCE_STAFF_HMB);

        setPlantCode(plantCode);
        setHmb(hmb);
        setVendor(vendor);
        setHmbName(hmbName);
        setStatus(status);
    }
}
