/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.records;


import com.jooq.jooq.model.tables.FiscalYear;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FiscalYearRecord extends UpdatableRecordImpl<FiscalYearRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor_portal_pbx.fiscal_year.ID</code>.
     */
    public FiscalYearRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.fiscal_year.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vendor_portal_pbx.fiscal_year.FISCAL_YEAR_VAL</code>.
     */
    public FiscalYearRecord setFiscalYearVal(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.fiscal_year.FISCAL_YEAR_VAL</code>.
     */
    public String getFiscalYearVal() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vendor_portal_pbx.fiscal_year.FISCAL_YEAR_NAME</code>.
     */
    public FiscalYearRecord setFiscalYearName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.fiscal_year.FISCAL_YEAR_NAME</code>.
     */
    public String getFiscalYearName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vendor_portal_pbx.fiscal_year.STATUS</code>.
     */
    public FiscalYearRecord setStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.fiscal_year.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return FiscalYear.FISCAL_YEAR.ID;
    }

    @Override
    public Field<String> field2() {
        return FiscalYear.FISCAL_YEAR.FISCAL_YEAR_VAL;
    }

    @Override
    public Field<String> field3() {
        return FiscalYear.FISCAL_YEAR.FISCAL_YEAR_NAME;
    }

    @Override
    public Field<String> field4() {
        return FiscalYear.FISCAL_YEAR.STATUS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getFiscalYearVal();
    }

    @Override
    public String component3() {
        return getFiscalYearName();
    }

    @Override
    public String component4() {
        return getStatus();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getFiscalYearVal();
    }

    @Override
    public String value3() {
        return getFiscalYearName();
    }

    @Override
    public String value4() {
        return getStatus();
    }

    @Override
    public FiscalYearRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FiscalYearRecord value2(String value) {
        setFiscalYearVal(value);
        return this;
    }

    @Override
    public FiscalYearRecord value3(String value) {
        setFiscalYearName(value);
        return this;
    }

    @Override
    public FiscalYearRecord value4(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public FiscalYearRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FiscalYearRecord
     */
    public FiscalYearRecord() {
        super(FiscalYear.FISCAL_YEAR);
    }

    /**
     * Create a detached, initialised FiscalYearRecord
     */
    public FiscalYearRecord(Integer id, String fiscalYearVal, String fiscalYearName, String status) {
        super(FiscalYear.FISCAL_YEAR);

        setId(id);
        setFiscalYearVal(fiscalYearVal);
        setFiscalYearName(fiscalYearName);
        setStatus(status);
    }
}
