/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.records;


import com.jooq.jooq.model.tables.GrnCustomerDispachHeader;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Record4;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GrnCustomerDispachHeaderRecord extends UpdatableRecordImpl<GrnCustomerDispachHeaderRecord> implements Record15<String, String, String, LocalDate, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor_portal_pbx.grn_customer_dispach_header.COMP_CODE</code>.
     */
    public GrnCustomerDispachHeaderRecord setCompCode(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.grn_customer_dispach_header.COMP_CODE</code>.
     */
    public String getCompCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>vendor_portal_pbx.grn_customer_dispach_header.CUSTOMER_CODE</code>.
     */
    public GrnCustomerDispachHeaderRecord setCustomerCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.grn_customer_dispach_header.CUSTOMER_CODE</code>.
     */
    public String getCustomerCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vendor_portal_pbx.grn_customer_dispach_header.MODEL</code>.
     */
    public GrnCustomerDispachHeaderRecord setModel(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.grn_customer_dispach_header.MODEL</code>.
     */
    public String getModel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vendor_portal_pbx.grn_customer_dispach_header.ASSET_REQ_DATE</code>.
     */
    public GrnCustomerDispachHeaderRecord setAssetReqDate(LocalDate value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.grn_customer_dispach_header.ASSET_REQ_DATE</code>.
     */
    public LocalDate getAssetReqDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>vendor_portal_pbx.grn_customer_dispach_header.CUSTOMER_NAME</code>.
     */
    public GrnCustomerDispachHeaderRecord setCustomerName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.grn_customer_dispach_header.CUSTOMER_NAME</code>.
     */
    public String getCustomerName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vendor_portal_pbx.grn_customer_dispach_header.RSM_NAME</code>.
     */
    public GrnCustomerDispachHeaderRecord setRsmName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.grn_customer_dispach_header.RSM_NAME</code>.
     */
    public String getRsmName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>vendor_portal_pbx.grn_customer_dispach_header.QTY</code>.
     */
    public GrnCustomerDispachHeaderRecord setQty(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.grn_customer_dispach_header.QTY</code>.
     */
    public String getQty() {
        return (String) get(6);
    }

    /**
     * Setter for <code>vendor_portal_pbx.grn_customer_dispach_header.STATUS</code>.
     */
    public GrnCustomerDispachHeaderRecord setStatus(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.grn_customer_dispach_header.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>vendor_portal_pbx.grn_customer_dispach_header.CREATED_BY</code>.
     */
    public GrnCustomerDispachHeaderRecord setCreatedBy(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.grn_customer_dispach_header.CREATED_BY</code>.
     */
    public String getCreatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>vendor_portal_pbx.grn_customer_dispach_header.CREATED_ON</code>.
     */
    public GrnCustomerDispachHeaderRecord setCreatedOn(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.grn_customer_dispach_header.CREATED_ON</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>vendor_portal_pbx.grn_customer_dispach_header.UPDATED_BY</code>.
     */
    public GrnCustomerDispachHeaderRecord setUpdatedBy(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.grn_customer_dispach_header.UPDATED_BY</code>.
     */
    public String getUpdatedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>vendor_portal_pbx.grn_customer_dispach_header.UPDATED_ON</code>.
     */
    public GrnCustomerDispachHeaderRecord setUpdatedOn(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.grn_customer_dispach_header.UPDATED_ON</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>vendor_portal_pbx.grn_customer_dispach_header.CFA_CODE</code>.
     */
    public GrnCustomerDispachHeaderRecord setCfaCode(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.grn_customer_dispach_header.CFA_CODE</code>.
     */
    public String getCfaCode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>vendor_portal_pbx.grn_customer_dispach_header.CFA_NAME</code>.
     */
    public GrnCustomerDispachHeaderRecord setCfaName(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.grn_customer_dispach_header.CFA_NAME</code>.
     */
    public String getCfaName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>vendor_portal_pbx.grn_customer_dispach_header.DC_ATTACHMENT_URL</code>.
     */
    public GrnCustomerDispachHeaderRecord setDcAttachmentUrl(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.grn_customer_dispach_header.DC_ATTACHMENT_URL</code>.
     */
    public String getDcAttachmentUrl() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record4<String, String, String, LocalDate> key() {
        return (Record4) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<String, String, String, LocalDate, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String, String, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<String, String, String, LocalDate, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String, String, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER.COMP_CODE;
    }

    @Override
    public Field<String> field2() {
        return GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER.CUSTOMER_CODE;
    }

    @Override
    public Field<String> field3() {
        return GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER.MODEL;
    }

    @Override
    public Field<LocalDate> field4() {
        return GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER.ASSET_REQ_DATE;
    }

    @Override
    public Field<String> field5() {
        return GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER.CUSTOMER_NAME;
    }

    @Override
    public Field<String> field6() {
        return GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER.RSM_NAME;
    }

    @Override
    public Field<String> field7() {
        return GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER.QTY;
    }

    @Override
    public Field<String> field8() {
        return GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER.STATUS;
    }

    @Override
    public Field<String> field9() {
        return GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER.CREATED_ON;
    }

    @Override
    public Field<String> field11() {
        return GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER.UPDATED_BY;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER.UPDATED_ON;
    }

    @Override
    public Field<String> field13() {
        return GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER.CFA_CODE;
    }

    @Override
    public Field<String> field14() {
        return GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER.CFA_NAME;
    }

    @Override
    public Field<String> field15() {
        return GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER.DC_ATTACHMENT_URL;
    }

    @Override
    public String component1() {
        return getCompCode();
    }

    @Override
    public String component2() {
        return getCustomerCode();
    }

    @Override
    public String component3() {
        return getModel();
    }

    @Override
    public LocalDate component4() {
        return getAssetReqDate();
    }

    @Override
    public String component5() {
        return getCustomerName();
    }

    @Override
    public String component6() {
        return getRsmName();
    }

    @Override
    public String component7() {
        return getQty();
    }

    @Override
    public String component8() {
        return getStatus();
    }

    @Override
    public String component9() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component10() {
        return getCreatedOn();
    }

    @Override
    public String component11() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime component12() {
        return getUpdatedOn();
    }

    @Override
    public String component13() {
        return getCfaCode();
    }

    @Override
    public String component14() {
        return getCfaName();
    }

    @Override
    public String component15() {
        return getDcAttachmentUrl();
    }

    @Override
    public String value1() {
        return getCompCode();
    }

    @Override
    public String value2() {
        return getCustomerCode();
    }

    @Override
    public String value3() {
        return getModel();
    }

    @Override
    public LocalDate value4() {
        return getAssetReqDate();
    }

    @Override
    public String value5() {
        return getCustomerName();
    }

    @Override
    public String value6() {
        return getRsmName();
    }

    @Override
    public String value7() {
        return getQty();
    }

    @Override
    public String value8() {
        return getStatus();
    }

    @Override
    public String value9() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value10() {
        return getCreatedOn();
    }

    @Override
    public String value11() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime value12() {
        return getUpdatedOn();
    }

    @Override
    public String value13() {
        return getCfaCode();
    }

    @Override
    public String value14() {
        return getCfaName();
    }

    @Override
    public String value15() {
        return getDcAttachmentUrl();
    }

    @Override
    public GrnCustomerDispachHeaderRecord value1(String value) {
        setCompCode(value);
        return this;
    }

    @Override
    public GrnCustomerDispachHeaderRecord value2(String value) {
        setCustomerCode(value);
        return this;
    }

    @Override
    public GrnCustomerDispachHeaderRecord value3(String value) {
        setModel(value);
        return this;
    }

    @Override
    public GrnCustomerDispachHeaderRecord value4(LocalDate value) {
        setAssetReqDate(value);
        return this;
    }

    @Override
    public GrnCustomerDispachHeaderRecord value5(String value) {
        setCustomerName(value);
        return this;
    }

    @Override
    public GrnCustomerDispachHeaderRecord value6(String value) {
        setRsmName(value);
        return this;
    }

    @Override
    public GrnCustomerDispachHeaderRecord value7(String value) {
        setQty(value);
        return this;
    }

    @Override
    public GrnCustomerDispachHeaderRecord value8(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public GrnCustomerDispachHeaderRecord value9(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public GrnCustomerDispachHeaderRecord value10(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public GrnCustomerDispachHeaderRecord value11(String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public GrnCustomerDispachHeaderRecord value12(LocalDateTime value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public GrnCustomerDispachHeaderRecord value13(String value) {
        setCfaCode(value);
        return this;
    }

    @Override
    public GrnCustomerDispachHeaderRecord value14(String value) {
        setCfaName(value);
        return this;
    }

    @Override
    public GrnCustomerDispachHeaderRecord value15(String value) {
        setDcAttachmentUrl(value);
        return this;
    }

    @Override
    public GrnCustomerDispachHeaderRecord values(String value1, String value2, String value3, LocalDate value4, String value5, String value6, String value7, String value8, String value9, LocalDateTime value10, String value11, LocalDateTime value12, String value13, String value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GrnCustomerDispachHeaderRecord
     */
    public GrnCustomerDispachHeaderRecord() {
        super(GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER);
    }

    /**
     * Create a detached, initialised GrnCustomerDispachHeaderRecord
     */
    public GrnCustomerDispachHeaderRecord(String compCode, String customerCode, String model, LocalDate assetReqDate, String customerName, String rsmName, String qty, String status, String createdBy, LocalDateTime createdOn, String updatedBy, LocalDateTime updatedOn, String cfaCode, String cfaName, String dcAttachmentUrl) {
        super(GrnCustomerDispachHeader.GRN_CUSTOMER_DISPACH_HEADER);

        setCompCode(compCode);
        setCustomerCode(customerCode);
        setModel(model);
        setAssetReqDate(assetReqDate);
        setCustomerName(customerName);
        setRsmName(rsmName);
        setQty(qty);
        setStatus(status);
        setCreatedBy(createdBy);
        setCreatedOn(createdOn);
        setUpdatedBy(updatedBy);
        setUpdatedOn(updatedOn);
        setCfaCode(cfaCode);
        setCfaName(cfaName);
        setDcAttachmentUrl(dcAttachmentUrl);
    }
}
