/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.records;


import com.jooq.jooq.model.tables.IvrSubDivisionMaster;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IvrSubDivisionMasterRecord extends UpdatableRecordImpl<IvrSubDivisionMasterRecord> implements Record8<Integer, Integer, String, String, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor_portal_pbx.ivr_sub_division_master.SUB_DIVISION_ID</code>.
     */
    public IvrSubDivisionMasterRecord setSubDivisionId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_sub_division_master.SUB_DIVISION_ID</code>.
     */
    public Integer getSubDivisionId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_sub_division_master.DIVISION_ID</code>.
     */
    public IvrSubDivisionMasterRecord setDivisionId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_sub_division_master.DIVISION_ID</code>.
     */
    public Integer getDivisionId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_sub_division_master.SUB_DIVISION_NAME</code>.
     */
    public IvrSubDivisionMasterRecord setSubDivisionName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_sub_division_master.SUB_DIVISION_NAME</code>.
     */
    public String getSubDivisionName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_sub_division_master.STATUS</code>.
     */
    public IvrSubDivisionMasterRecord setStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_sub_division_master.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_sub_division_master.CREATED_BY</code>.
     */
    public IvrSubDivisionMasterRecord setCreatedBy(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_sub_division_master.CREATED_BY</code>.
     */
    public String getCreatedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_sub_division_master.CREATED_ON</code>.
     */
    public IvrSubDivisionMasterRecord setCreatedOn(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_sub_division_master.CREATED_ON</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_sub_division_master.UPDATED_BY</code>.
     */
    public IvrSubDivisionMasterRecord setUpdatedBy(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_sub_division_master.UPDATED_BY</code>.
     */
    public String getUpdatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>vendor_portal_pbx.ivr_sub_division_master.UPDATED_ON</code>.
     */
    public IvrSubDivisionMasterRecord setUpdatedOn(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.ivr_sub_division_master.UPDATED_ON</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, String, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, String, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return IvrSubDivisionMaster.IVR_SUB_DIVISION_MASTER.SUB_DIVISION_ID;
    }

    @Override
    public Field<Integer> field2() {
        return IvrSubDivisionMaster.IVR_SUB_DIVISION_MASTER.DIVISION_ID;
    }

    @Override
    public Field<String> field3() {
        return IvrSubDivisionMaster.IVR_SUB_DIVISION_MASTER.SUB_DIVISION_NAME;
    }

    @Override
    public Field<String> field4() {
        return IvrSubDivisionMaster.IVR_SUB_DIVISION_MASTER.STATUS;
    }

    @Override
    public Field<String> field5() {
        return IvrSubDivisionMaster.IVR_SUB_DIVISION_MASTER.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return IvrSubDivisionMaster.IVR_SUB_DIVISION_MASTER.CREATED_ON;
    }

    @Override
    public Field<String> field7() {
        return IvrSubDivisionMaster.IVR_SUB_DIVISION_MASTER.UPDATED_BY;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return IvrSubDivisionMaster.IVR_SUB_DIVISION_MASTER.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getSubDivisionId();
    }

    @Override
    public Integer component2() {
        return getDivisionId();
    }

    @Override
    public String component3() {
        return getSubDivisionName();
    }

    @Override
    public String component4() {
        return getStatus();
    }

    @Override
    public String component5() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedOn();
    }

    @Override
    public String component7() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getSubDivisionId();
    }

    @Override
    public Integer value2() {
        return getDivisionId();
    }

    @Override
    public String value3() {
        return getSubDivisionName();
    }

    @Override
    public String value4() {
        return getStatus();
    }

    @Override
    public String value5() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedOn();
    }

    @Override
    public String value7() {
        return getUpdatedBy();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdatedOn();
    }

    @Override
    public IvrSubDivisionMasterRecord value1(Integer value) {
        setSubDivisionId(value);
        return this;
    }

    @Override
    public IvrSubDivisionMasterRecord value2(Integer value) {
        setDivisionId(value);
        return this;
    }

    @Override
    public IvrSubDivisionMasterRecord value3(String value) {
        setSubDivisionName(value);
        return this;
    }

    @Override
    public IvrSubDivisionMasterRecord value4(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public IvrSubDivisionMasterRecord value5(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public IvrSubDivisionMasterRecord value6(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public IvrSubDivisionMasterRecord value7(String value) {
        setUpdatedBy(value);
        return this;
    }

    @Override
    public IvrSubDivisionMasterRecord value8(LocalDateTime value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public IvrSubDivisionMasterRecord values(Integer value1, Integer value2, String value3, String value4, String value5, LocalDateTime value6, String value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IvrSubDivisionMasterRecord
     */
    public IvrSubDivisionMasterRecord() {
        super(IvrSubDivisionMaster.IVR_SUB_DIVISION_MASTER);
    }

    /**
     * Create a detached, initialised IvrSubDivisionMasterRecord
     */
    public IvrSubDivisionMasterRecord(Integer subDivisionId, Integer divisionId, String subDivisionName, String status, String createdBy, LocalDateTime createdOn, String updatedBy, LocalDateTime updatedOn) {
        super(IvrSubDivisionMaster.IVR_SUB_DIVISION_MASTER);

        setSubDivisionId(subDivisionId);
        setDivisionId(divisionId);
        setSubDivisionName(subDivisionName);
        setStatus(status);
        setCreatedBy(createdBy);
        setCreatedOn(createdOn);
        setUpdatedBy(updatedBy);
        setUpdatedOn(updatedOn);
    }
}
