/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.records;


import com.jooq.jooq.model.tables.TcPlantVisit;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Record2;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TcPlantVisitRecord extends UpdatableRecordImpl<TcPlantVisitRecord> implements Record10<String, String, LocalDate, Integer, LocalTime, LocalTime, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor_portal_pbx.TC_PLANT_VISIT.REQUEST_ID</code>.
     */
    public TcPlantVisitRecord setRequestId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_PLANT_VISIT.REQUEST_ID</code>.
     */
    public String getRequestId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_PLANT_VISIT.PLANT_CODE</code>.
     */
    public TcPlantVisitRecord setPlantCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_PLANT_VISIT.PLANT_CODE</code>.
     */
    public String getPlantCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_PLANT_VISIT.VISIT_DATE</code>.
     */
    public TcPlantVisitRecord setVisitDate(LocalDate value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_PLANT_VISIT.VISIT_DATE</code>.
     */
    public LocalDate getVisitDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_PLANT_VISIT.ROUTE_CODE</code>.
     */
    public TcPlantVisitRecord setRouteCode(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_PLANT_VISIT.ROUTE_CODE</code>.
     */
    public Integer getRouteCode() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_PLANT_VISIT.START_TIME</code>.
     */
    public TcPlantVisitRecord setStartTime(LocalTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_PLANT_VISIT.START_TIME</code>.
     */
    public LocalTime getStartTime() {
        return (LocalTime) get(4);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_PLANT_VISIT.END_TIME</code>.
     */
    public TcPlantVisitRecord setEndTime(LocalTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_PLANT_VISIT.END_TIME</code>.
     */
    public LocalTime getEndTime() {
        return (LocalTime) get(5);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_PLANT_VISIT.CREATED_BY</code>.
     */
    public TcPlantVisitRecord setCreatedBy(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_PLANT_VISIT.CREATED_BY</code>.
     */
    public String getCreatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_PLANT_VISIT.CREATED_ON</code>.
     */
    public TcPlantVisitRecord setCreatedOn(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_PLANT_VISIT.CREATED_ON</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_PLANT_VISIT.LAST_CHANGED_BY</code>.
     */
    public TcPlantVisitRecord setLastChangedBy(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_PLANT_VISIT.LAST_CHANGED_BY</code>.
     */
    public String getLastChangedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_PLANT_VISIT.LAST_CHANGED_ON</code>.
     */
    public TcPlantVisitRecord setLastChangedOn(LocalDateTime value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_PLANT_VISIT.LAST_CHANGED_ON</code>.
     */
    public LocalDateTime getLastChangedOn() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<String, String, LocalDate, Integer, LocalTime, LocalTime, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<String, String, LocalDate, Integer, LocalTime, LocalTime, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TcPlantVisit.TC_PLANT_VISIT.REQUEST_ID;
    }

    @Override
    public Field<String> field2() {
        return TcPlantVisit.TC_PLANT_VISIT.PLANT_CODE;
    }

    @Override
    public Field<LocalDate> field3() {
        return TcPlantVisit.TC_PLANT_VISIT.VISIT_DATE;
    }

    @Override
    public Field<Integer> field4() {
        return TcPlantVisit.TC_PLANT_VISIT.ROUTE_CODE;
    }

    @Override
    public Field<LocalTime> field5() {
        return TcPlantVisit.TC_PLANT_VISIT.START_TIME;
    }

    @Override
    public Field<LocalTime> field6() {
        return TcPlantVisit.TC_PLANT_VISIT.END_TIME;
    }

    @Override
    public Field<String> field7() {
        return TcPlantVisit.TC_PLANT_VISIT.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return TcPlantVisit.TC_PLANT_VISIT.CREATED_ON;
    }

    @Override
    public Field<String> field9() {
        return TcPlantVisit.TC_PLANT_VISIT.LAST_CHANGED_BY;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return TcPlantVisit.TC_PLANT_VISIT.LAST_CHANGED_ON;
    }

    @Override
    public String component1() {
        return getRequestId();
    }

    @Override
    public String component2() {
        return getPlantCode();
    }

    @Override
    public LocalDate component3() {
        return getVisitDate();
    }

    @Override
    public Integer component4() {
        return getRouteCode();
    }

    @Override
    public LocalTime component5() {
        return getStartTime();
    }

    @Override
    public LocalTime component6() {
        return getEndTime();
    }

    @Override
    public String component7() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component8() {
        return getCreatedOn();
    }

    @Override
    public String component9() {
        return getLastChangedBy();
    }

    @Override
    public LocalDateTime component10() {
        return getLastChangedOn();
    }

    @Override
    public String value1() {
        return getRequestId();
    }

    @Override
    public String value2() {
        return getPlantCode();
    }

    @Override
    public LocalDate value3() {
        return getVisitDate();
    }

    @Override
    public Integer value4() {
        return getRouteCode();
    }

    @Override
    public LocalTime value5() {
        return getStartTime();
    }

    @Override
    public LocalTime value6() {
        return getEndTime();
    }

    @Override
    public String value7() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value8() {
        return getCreatedOn();
    }

    @Override
    public String value9() {
        return getLastChangedBy();
    }

    @Override
    public LocalDateTime value10() {
        return getLastChangedOn();
    }

    @Override
    public TcPlantVisitRecord value1(String value) {
        setRequestId(value);
        return this;
    }

    @Override
    public TcPlantVisitRecord value2(String value) {
        setPlantCode(value);
        return this;
    }

    @Override
    public TcPlantVisitRecord value3(LocalDate value) {
        setVisitDate(value);
        return this;
    }

    @Override
    public TcPlantVisitRecord value4(Integer value) {
        setRouteCode(value);
        return this;
    }

    @Override
    public TcPlantVisitRecord value5(LocalTime value) {
        setStartTime(value);
        return this;
    }

    @Override
    public TcPlantVisitRecord value6(LocalTime value) {
        setEndTime(value);
        return this;
    }

    @Override
    public TcPlantVisitRecord value7(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public TcPlantVisitRecord value8(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public TcPlantVisitRecord value9(String value) {
        setLastChangedBy(value);
        return this;
    }

    @Override
    public TcPlantVisitRecord value10(LocalDateTime value) {
        setLastChangedOn(value);
        return this;
    }

    @Override
    public TcPlantVisitRecord values(String value1, String value2, LocalDate value3, Integer value4, LocalTime value5, LocalTime value6, String value7, LocalDateTime value8, String value9, LocalDateTime value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TcPlantVisitRecord
     */
    public TcPlantVisitRecord() {
        super(TcPlantVisit.TC_PLANT_VISIT);
    }

    /**
     * Create a detached, initialised TcPlantVisitRecord
     */
    public TcPlantVisitRecord(String requestId, String plantCode, LocalDate visitDate, Integer routeCode, LocalTime startTime, LocalTime endTime, String createdBy, LocalDateTime createdOn, String lastChangedBy, LocalDateTime lastChangedOn) {
        super(TcPlantVisit.TC_PLANT_VISIT);

        setRequestId(requestId);
        setPlantCode(plantCode);
        setVisitDate(visitDate);
        setRouteCode(routeCode);
        setStartTime(startTime);
        setEndTime(endTime);
        setCreatedBy(createdBy);
        setCreatedOn(createdOn);
        setLastChangedBy(lastChangedBy);
        setLastChangedOn(lastChangedOn);
    }
}
