/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.records;


import com.jooq.jooq.model.tables.TcUserRoleDept;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TcUserRoleDeptRecord extends UpdatableRecordImpl<TcUserRoleDeptRecord> implements Record9<String, Integer, Integer, String, String, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.USER_ID</code>.
     */
    public TcUserRoleDeptRecord setUserId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.USER_ID</code>.
     */
    public String getUserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.USER_TYPE_ID</code>.
     */
    public TcUserRoleDeptRecord setUserTypeId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.USER_TYPE_ID</code>.
     */
    public Integer getUserTypeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.ROLE_ID</code>.
     */
    public TcUserRoleDeptRecord setRoleId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.ROLE_ID</code>.
     */
    public Integer getRoleId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.DEPT_ID</code>.
     */
    public TcUserRoleDeptRecord setDeptId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.DEPT_ID</code>.
     */
    public String getDeptId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.STATUS</code>.
     */
    public TcUserRoleDeptRecord setStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.CREATED_BY</code>.
     */
    public TcUserRoleDeptRecord setCreatedBy(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.CREATED_BY</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.CREATED_ON</code>.
     */
    public TcUserRoleDeptRecord setCreatedOn(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.CREATED_ON</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.LAST_CHANGED_BY</code>.
     */
    public TcUserRoleDeptRecord setLastChangedBy(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.LAST_CHANGED_BY</code>.
     */
    public String getLastChangedBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.LAST_CHANGED_ON</code>.
     */
    public TcUserRoleDeptRecord setLastChangedOn(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_USER_ROLE_DEPT.LAST_CHANGED_ON</code>.
     */
    public LocalDateTime getLastChangedOn() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record4<String, Integer, Integer, String> key() {
        return (Record4) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<String, Integer, Integer, String, String, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<String, Integer, Integer, String, String, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TcUserRoleDept.TC_USER_ROLE_DEPT.USER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return TcUserRoleDept.TC_USER_ROLE_DEPT.USER_TYPE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return TcUserRoleDept.TC_USER_ROLE_DEPT.ROLE_ID;
    }

    @Override
    public Field<String> field4() {
        return TcUserRoleDept.TC_USER_ROLE_DEPT.DEPT_ID;
    }

    @Override
    public Field<String> field5() {
        return TcUserRoleDept.TC_USER_ROLE_DEPT.STATUS;
    }

    @Override
    public Field<String> field6() {
        return TcUserRoleDept.TC_USER_ROLE_DEPT.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return TcUserRoleDept.TC_USER_ROLE_DEPT.CREATED_ON;
    }

    @Override
    public Field<String> field8() {
        return TcUserRoleDept.TC_USER_ROLE_DEPT.LAST_CHANGED_BY;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return TcUserRoleDept.TC_USER_ROLE_DEPT.LAST_CHANGED_ON;
    }

    @Override
    public String component1() {
        return getUserId();
    }

    @Override
    public Integer component2() {
        return getUserTypeId();
    }

    @Override
    public Integer component3() {
        return getRoleId();
    }

    @Override
    public String component4() {
        return getDeptId();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public String component6() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedOn();
    }

    @Override
    public String component8() {
        return getLastChangedBy();
    }

    @Override
    public LocalDateTime component9() {
        return getLastChangedOn();
    }

    @Override
    public String value1() {
        return getUserId();
    }

    @Override
    public Integer value2() {
        return getUserTypeId();
    }

    @Override
    public Integer value3() {
        return getRoleId();
    }

    @Override
    public String value4() {
        return getDeptId();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public String value6() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedOn();
    }

    @Override
    public String value8() {
        return getLastChangedBy();
    }

    @Override
    public LocalDateTime value9() {
        return getLastChangedOn();
    }

    @Override
    public TcUserRoleDeptRecord value1(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public TcUserRoleDeptRecord value2(Integer value) {
        setUserTypeId(value);
        return this;
    }

    @Override
    public TcUserRoleDeptRecord value3(Integer value) {
        setRoleId(value);
        return this;
    }

    @Override
    public TcUserRoleDeptRecord value4(String value) {
        setDeptId(value);
        return this;
    }

    @Override
    public TcUserRoleDeptRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public TcUserRoleDeptRecord value6(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public TcUserRoleDeptRecord value7(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public TcUserRoleDeptRecord value8(String value) {
        setLastChangedBy(value);
        return this;
    }

    @Override
    public TcUserRoleDeptRecord value9(LocalDateTime value) {
        setLastChangedOn(value);
        return this;
    }

    @Override
    public TcUserRoleDeptRecord values(String value1, Integer value2, Integer value3, String value4, String value5, String value6, LocalDateTime value7, String value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TcUserRoleDeptRecord
     */
    public TcUserRoleDeptRecord() {
        super(TcUserRoleDept.TC_USER_ROLE_DEPT);
    }

    /**
     * Create a detached, initialised TcUserRoleDeptRecord
     */
    public TcUserRoleDeptRecord(String userId, Integer userTypeId, Integer roleId, String deptId, String status, String createdBy, LocalDateTime createdOn, String lastChangedBy, LocalDateTime lastChangedOn) {
        super(TcUserRoleDept.TC_USER_ROLE_DEPT);

        setUserId(userId);
        setUserTypeId(userTypeId);
        setRoleId(roleId);
        setDeptId(deptId);
        setStatus(status);
        setCreatedBy(createdBy);
        setCreatedOn(createdOn);
        setLastChangedBy(lastChangedBy);
        setLastChangedOn(lastChangedOn);
    }
}
