/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.records;


import com.jooq.jooq.model.tables.TcUserTrainingCenterMaster;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TcUserTrainingCenterMasterRecord extends UpdatableRecordImpl<TcUserTrainingCenterMasterRecord> implements Record5<String, Integer, LocalDate, LocalDate, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER.USER_ID</code>.
     */
    public TcUserTrainingCenterMasterRecord setUserId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER.USER_ID</code>.
     */
    public String getUserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER.TR_CENTER_CODE</code>.
     */
    public TcUserTrainingCenterMasterRecord setTrCenterCode(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER.TR_CENTER_CODE</code>.
     */
    public Integer getTrCenterCode() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER.FROM_DATE</code>.
     */
    public TcUserTrainingCenterMasterRecord setFromDate(LocalDate value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER.FROM_DATE</code>.
     */
    public LocalDate getFromDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER.TO_DATE</code>.
     */
    public TcUserTrainingCenterMasterRecord setToDate(LocalDate value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER.TO_DATE</code>.
     */
    public LocalDate getToDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER.STATUS</code>.
     */
    public TcUserTrainingCenterMasterRecord setStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.TC_USER_TRAINING_CENTER_MASTER.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, Integer, LocalDate, LocalDate, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, Integer, LocalDate, LocalDate, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TcUserTrainingCenterMaster.TC_USER_TRAINING_CENTER_MASTER.USER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return TcUserTrainingCenterMaster.TC_USER_TRAINING_CENTER_MASTER.TR_CENTER_CODE;
    }

    @Override
    public Field<LocalDate> field3() {
        return TcUserTrainingCenterMaster.TC_USER_TRAINING_CENTER_MASTER.FROM_DATE;
    }

    @Override
    public Field<LocalDate> field4() {
        return TcUserTrainingCenterMaster.TC_USER_TRAINING_CENTER_MASTER.TO_DATE;
    }

    @Override
    public Field<String> field5() {
        return TcUserTrainingCenterMaster.TC_USER_TRAINING_CENTER_MASTER.STATUS;
    }

    @Override
    public String component1() {
        return getUserId();
    }

    @Override
    public Integer component2() {
        return getTrCenterCode();
    }

    @Override
    public LocalDate component3() {
        return getFromDate();
    }

    @Override
    public LocalDate component4() {
        return getToDate();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public String value1() {
        return getUserId();
    }

    @Override
    public Integer value2() {
        return getTrCenterCode();
    }

    @Override
    public LocalDate value3() {
        return getFromDate();
    }

    @Override
    public LocalDate value4() {
        return getToDate();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public TcUserTrainingCenterMasterRecord value1(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public TcUserTrainingCenterMasterRecord value2(Integer value) {
        setTrCenterCode(value);
        return this;
    }

    @Override
    public TcUserTrainingCenterMasterRecord value3(LocalDate value) {
        setFromDate(value);
        return this;
    }

    @Override
    public TcUserTrainingCenterMasterRecord value4(LocalDate value) {
        setToDate(value);
        return this;
    }

    @Override
    public TcUserTrainingCenterMasterRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public TcUserTrainingCenterMasterRecord values(String value1, Integer value2, LocalDate value3, LocalDate value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TcUserTrainingCenterMasterRecord
     */
    public TcUserTrainingCenterMasterRecord() {
        super(TcUserTrainingCenterMaster.TC_USER_TRAINING_CENTER_MASTER);
    }

    /**
     * Create a detached, initialised TcUserTrainingCenterMasterRecord
     */
    public TcUserTrainingCenterMasterRecord(String userId, Integer trCenterCode, LocalDate fromDate, LocalDate toDate, String status) {
        super(TcUserTrainingCenterMaster.TC_USER_TRAINING_CENTER_MASTER);

        setUserId(userId);
        setTrCenterCode(trCenterCode);
        setFromDate(fromDate);
        setToDate(toDate);
        setStatus(status);
    }
}
