/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.records;


import com.jooq.jooq.model.tables.TransporterSummary;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record13;
import org.jooq.Record3;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransporterSummaryRecord extends UpdatableRecordImpl<TransporterSummaryRecord> implements Record13<String, LocalDateTime, LocalDateTime, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor_portal_pbx.transporter_summary.VENDOR_CODE</code>.
     */
    public TransporterSummaryRecord setVendorCode(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.transporter_summary.VENDOR_CODE</code>.
     */
    public String getVendorCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>vendor_portal_pbx.transporter_summary.FROM_DATE</code>.
     */
    public TransporterSummaryRecord setFromDate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.transporter_summary.FROM_DATE</code>.
     */
    public LocalDateTime getFromDate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>vendor_portal_pbx.transporter_summary.TO_DATE</code>.
     */
    public TransporterSummaryRecord setToDate(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.transporter_summary.TO_DATE</code>.
     */
    public LocalDateTime getToDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>vendor_portal_pbx.transporter_summary.VEHICLE_NO</code>.
     */
    public TransporterSummaryRecord setVehicleNo(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.transporter_summary.VEHICLE_NO</code>.
     */
    public String getVehicleNo() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vendor_portal_pbx.transporter_summary.PAYMENT</code>.
     */
    public TransporterSummaryRecord setPayment(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.transporter_summary.PAYMENT</code>.
     */
    public String getPayment() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vendor_portal_pbx.transporter_summary.DIESEL_NO</code>.
     */
    public TransporterSummaryRecord setDieselNo(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.transporter_summary.DIESEL_NO</code>.
     */
    public String getDieselNo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>vendor_portal_pbx.transporter_summary.SD</code>.
     */
    public TransporterSummaryRecord setSd(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.transporter_summary.SD</code>.
     */
    public String getSd() {
        return (String) get(6);
    }

    /**
     * Setter for <code>vendor_portal_pbx.transporter_summary.GPS</code>.
     */
    public TransporterSummaryRecord setGps(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.transporter_summary.GPS</code>.
     */
    public String getGps() {
        return (String) get(7);
    }

    /**
     * Setter for <code>vendor_portal_pbx.transporter_summary.TDS</code>.
     */
    public TransporterSummaryRecord setTds(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.transporter_summary.TDS</code>.
     */
    public String getTds() {
        return (String) get(8);
    }

    /**
     * Setter for <code>vendor_portal_pbx.transporter_summary.ADDITION</code>.
     */
    public TransporterSummaryRecord setAddition(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.transporter_summary.ADDITION</code>.
     */
    public String getAddition() {
        return (String) get(9);
    }

    /**
     * Setter for <code>vendor_portal_pbx.transporter_summary.DEDUCTION</code>.
     */
    public TransporterSummaryRecord setDeduction(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.transporter_summary.DEDUCTION</code>.
     */
    public String getDeduction() {
        return (String) get(10);
    }

    /**
     * Setter for <code>vendor_portal_pbx.transporter_summary.GRAND_TOTAL</code>.
     */
    public TransporterSummaryRecord setGrandTotal(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.transporter_summary.GRAND_TOTAL</code>.
     */
    public String getGrandTotal() {
        return (String) get(11);
    }

    /**
     * Setter for <code>vendor_portal_pbx.transporter_summary.NET_PAYMENT_PAID</code>.
     */
    public TransporterSummaryRecord setNetPaymentPaid(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.transporter_summary.NET_PAYMENT_PAID</code>.
     */
    public String getNetPaymentPaid() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, LocalDateTime, LocalDateTime> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<String, LocalDateTime, LocalDateTime, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<String, LocalDateTime, LocalDateTime, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TransporterSummary.TRANSPORTER_SUMMARY.VENDOR_CODE;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return TransporterSummary.TRANSPORTER_SUMMARY.FROM_DATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return TransporterSummary.TRANSPORTER_SUMMARY.TO_DATE;
    }

    @Override
    public Field<String> field4() {
        return TransporterSummary.TRANSPORTER_SUMMARY.VEHICLE_NO;
    }

    @Override
    public Field<String> field5() {
        return TransporterSummary.TRANSPORTER_SUMMARY.PAYMENT;
    }

    @Override
    public Field<String> field6() {
        return TransporterSummary.TRANSPORTER_SUMMARY.DIESEL_NO;
    }

    @Override
    public Field<String> field7() {
        return TransporterSummary.TRANSPORTER_SUMMARY.SD;
    }

    @Override
    public Field<String> field8() {
        return TransporterSummary.TRANSPORTER_SUMMARY.GPS;
    }

    @Override
    public Field<String> field9() {
        return TransporterSummary.TRANSPORTER_SUMMARY.TDS;
    }

    @Override
    public Field<String> field10() {
        return TransporterSummary.TRANSPORTER_SUMMARY.ADDITION;
    }

    @Override
    public Field<String> field11() {
        return TransporterSummary.TRANSPORTER_SUMMARY.DEDUCTION;
    }

    @Override
    public Field<String> field12() {
        return TransporterSummary.TRANSPORTER_SUMMARY.GRAND_TOTAL;
    }

    @Override
    public Field<String> field13() {
        return TransporterSummary.TRANSPORTER_SUMMARY.NET_PAYMENT_PAID;
    }

    @Override
    public String component1() {
        return getVendorCode();
    }

    @Override
    public LocalDateTime component2() {
        return getFromDate();
    }

    @Override
    public LocalDateTime component3() {
        return getToDate();
    }

    @Override
    public String component4() {
        return getVehicleNo();
    }

    @Override
    public String component5() {
        return getPayment();
    }

    @Override
    public String component6() {
        return getDieselNo();
    }

    @Override
    public String component7() {
        return getSd();
    }

    @Override
    public String component8() {
        return getGps();
    }

    @Override
    public String component9() {
        return getTds();
    }

    @Override
    public String component10() {
        return getAddition();
    }

    @Override
    public String component11() {
        return getDeduction();
    }

    @Override
    public String component12() {
        return getGrandTotal();
    }

    @Override
    public String component13() {
        return getNetPaymentPaid();
    }

    @Override
    public String value1() {
        return getVendorCode();
    }

    @Override
    public LocalDateTime value2() {
        return getFromDate();
    }

    @Override
    public LocalDateTime value3() {
        return getToDate();
    }

    @Override
    public String value4() {
        return getVehicleNo();
    }

    @Override
    public String value5() {
        return getPayment();
    }

    @Override
    public String value6() {
        return getDieselNo();
    }

    @Override
    public String value7() {
        return getSd();
    }

    @Override
    public String value8() {
        return getGps();
    }

    @Override
    public String value9() {
        return getTds();
    }

    @Override
    public String value10() {
        return getAddition();
    }

    @Override
    public String value11() {
        return getDeduction();
    }

    @Override
    public String value12() {
        return getGrandTotal();
    }

    @Override
    public String value13() {
        return getNetPaymentPaid();
    }

    @Override
    public TransporterSummaryRecord value1(String value) {
        setVendorCode(value);
        return this;
    }

    @Override
    public TransporterSummaryRecord value2(LocalDateTime value) {
        setFromDate(value);
        return this;
    }

    @Override
    public TransporterSummaryRecord value3(LocalDateTime value) {
        setToDate(value);
        return this;
    }

    @Override
    public TransporterSummaryRecord value4(String value) {
        setVehicleNo(value);
        return this;
    }

    @Override
    public TransporterSummaryRecord value5(String value) {
        setPayment(value);
        return this;
    }

    @Override
    public TransporterSummaryRecord value6(String value) {
        setDieselNo(value);
        return this;
    }

    @Override
    public TransporterSummaryRecord value7(String value) {
        setSd(value);
        return this;
    }

    @Override
    public TransporterSummaryRecord value8(String value) {
        setGps(value);
        return this;
    }

    @Override
    public TransporterSummaryRecord value9(String value) {
        setTds(value);
        return this;
    }

    @Override
    public TransporterSummaryRecord value10(String value) {
        setAddition(value);
        return this;
    }

    @Override
    public TransporterSummaryRecord value11(String value) {
        setDeduction(value);
        return this;
    }

    @Override
    public TransporterSummaryRecord value12(String value) {
        setGrandTotal(value);
        return this;
    }

    @Override
    public TransporterSummaryRecord value13(String value) {
        setNetPaymentPaid(value);
        return this;
    }

    @Override
    public TransporterSummaryRecord values(String value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransporterSummaryRecord
     */
    public TransporterSummaryRecord() {
        super(TransporterSummary.TRANSPORTER_SUMMARY);
    }

    /**
     * Create a detached, initialised TransporterSummaryRecord
     */
    public TransporterSummaryRecord(String vendorCode, LocalDateTime fromDate, LocalDateTime toDate, String vehicleNo, String payment, String dieselNo, String sd, String gps, String tds, String addition, String deduction, String grandTotal, String netPaymentPaid) {
        super(TransporterSummary.TRANSPORTER_SUMMARY);

        setVendorCode(vendorCode);
        setFromDate(fromDate);
        setToDate(toDate);
        setVehicleNo(vehicleNo);
        setPayment(payment);
        setDieselNo(dieselNo);
        setSd(sd);
        setGps(gps);
        setTds(tds);
        setAddition(addition);
        setDeduction(deduction);
        setGrandTotal(grandTotal);
        setNetPaymentPaid(netPaymentPaid);
    }
}
