/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.records;


import com.jooq.jooq.model.tables.VendorContactHistory;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record16;
import org.jooq.Record3;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VendorContactHistoryRecord extends UpdatableRecordImpl<VendorContactHistoryRecord> implements Record16<String, String, String, String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String, String, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.VENDOR_CODE</code>.
     */
    public VendorContactHistoryRecord setVendorCode(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.VENDOR_CODE</code>.
     */
    public String getVendorCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.SERIAL_NO</code>.
     */
    public VendorContactHistoryRecord setSerialNo(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.SERIAL_NO</code>.
     */
    public String getSerialNo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.FLAG_TYPE</code>.
     */
    public VendorContactHistoryRecord setFlagType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.FLAG_TYPE</code>.
     */
    public String getFlagType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.CONTACT_PERSON_NAME</code>.
     */
    public VendorContactHistoryRecord setContactPersonName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.CONTACT_PERSON_NAME</code>.
     */
    public String getContactPersonName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.DESIGNATION</code>.
     */
    public VendorContactHistoryRecord setDesignation(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.DESIGNATION</code>.
     */
    public String getDesignation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.DEPARTMENT</code>.
     */
    public VendorContactHistoryRecord setDepartment(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.DEPARTMENT</code>.
     */
    public String getDepartment() {
        return (String) get(5);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.TELEPHONE_NO</code>.
     */
    public VendorContactHistoryRecord setTelephoneNo(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.TELEPHONE_NO</code>.
     */
    public String getTelephoneNo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.MOBILE_NO</code>.
     */
    public VendorContactHistoryRecord setMobileNo(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.MOBILE_NO</code>.
     */
    public String getMobileNo() {
        return (String) get(7);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.EMAIL_ID</code>.
     */
    public VendorContactHistoryRecord setEmailId(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.EMAIL_ID</code>.
     */
    public String getEmailId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.CREATED_BY</code>.
     */
    public VendorContactHistoryRecord setCreatedBy(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.CREATED_BY</code>.
     */
    public String getCreatedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.CREATED_ON</code>.
     */
    public VendorContactHistoryRecord setCreatedOn(LocalDateTime value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.CREATED_ON</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.LAST_CHANGED_BY</code>.
     */
    public VendorContactHistoryRecord setLastChangedBy(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.LAST_CHANGED_BY</code>.
     */
    public String getLastChangedBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.LAST_CHANGED_ON</code>.
     */
    public VendorContactHistoryRecord setLastChangedOn(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.LAST_CHANGED_ON</code>.
     */
    public LocalDateTime getLastChangedOn() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.CONTACT_DECLARATION_NAME</code>.
     */
    public VendorContactHistoryRecord setContactDeclarationName(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.CONTACT_DECLARATION_NAME</code>.
     */
    public String getContactDeclarationName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.CONTACT_DECLARATION_NO</code>.
     */
    public VendorContactHistoryRecord setContactDeclarationNo(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.CONTACT_DECLARATION_NO</code>.
     */
    public String getContactDeclarationNo() {
        return (String) get(14);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_contact_history.LAST_EDITED_ON</code>.
     */
    public VendorContactHistoryRecord setLastEditedOn(LocalDateTime value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_contact_history.LAST_EDITED_ON</code>.
     */
    public LocalDateTime getLastEditedOn() {
        return (LocalDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, LocalDateTime> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<String, String, String, String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String, String, LocalDateTime> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<String, String, String, String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, String, String, LocalDateTime> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.VENDOR_CODE;
    }

    @Override
    public Field<String> field2() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.SERIAL_NO;
    }

    @Override
    public Field<String> field3() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.FLAG_TYPE;
    }

    @Override
    public Field<String> field4() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.CONTACT_PERSON_NAME;
    }

    @Override
    public Field<String> field5() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.DESIGNATION;
    }

    @Override
    public Field<String> field6() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.DEPARTMENT;
    }

    @Override
    public Field<String> field7() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.TELEPHONE_NO;
    }

    @Override
    public Field<String> field8() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.MOBILE_NO;
    }

    @Override
    public Field<String> field9() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.EMAIL_ID;
    }

    @Override
    public Field<String> field10() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.CREATED_BY;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.CREATED_ON;
    }

    @Override
    public Field<String> field12() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.LAST_CHANGED_BY;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.LAST_CHANGED_ON;
    }

    @Override
    public Field<String> field14() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.CONTACT_DECLARATION_NAME;
    }

    @Override
    public Field<String> field15() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.CONTACT_DECLARATION_NO;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return VendorContactHistory.VENDOR_CONTACT_HISTORY.LAST_EDITED_ON;
    }

    @Override
    public String component1() {
        return getVendorCode();
    }

    @Override
    public String component2() {
        return getSerialNo();
    }

    @Override
    public String component3() {
        return getFlagType();
    }

    @Override
    public String component4() {
        return getContactPersonName();
    }

    @Override
    public String component5() {
        return getDesignation();
    }

    @Override
    public String component6() {
        return getDepartment();
    }

    @Override
    public String component7() {
        return getTelephoneNo();
    }

    @Override
    public String component8() {
        return getMobileNo();
    }

    @Override
    public String component9() {
        return getEmailId();
    }

    @Override
    public String component10() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime component11() {
        return getCreatedOn();
    }

    @Override
    public String component12() {
        return getLastChangedBy();
    }

    @Override
    public LocalDateTime component13() {
        return getLastChangedOn();
    }

    @Override
    public String component14() {
        return getContactDeclarationName();
    }

    @Override
    public String component15() {
        return getContactDeclarationNo();
    }

    @Override
    public LocalDateTime component16() {
        return getLastEditedOn();
    }

    @Override
    public String value1() {
        return getVendorCode();
    }

    @Override
    public String value2() {
        return getSerialNo();
    }

    @Override
    public String value3() {
        return getFlagType();
    }

    @Override
    public String value4() {
        return getContactPersonName();
    }

    @Override
    public String value5() {
        return getDesignation();
    }

    @Override
    public String value6() {
        return getDepartment();
    }

    @Override
    public String value7() {
        return getTelephoneNo();
    }

    @Override
    public String value8() {
        return getMobileNo();
    }

    @Override
    public String value9() {
        return getEmailId();
    }

    @Override
    public String value10() {
        return getCreatedBy();
    }

    @Override
    public LocalDateTime value11() {
        return getCreatedOn();
    }

    @Override
    public String value12() {
        return getLastChangedBy();
    }

    @Override
    public LocalDateTime value13() {
        return getLastChangedOn();
    }

    @Override
    public String value14() {
        return getContactDeclarationName();
    }

    @Override
    public String value15() {
        return getContactDeclarationNo();
    }

    @Override
    public LocalDateTime value16() {
        return getLastEditedOn();
    }

    @Override
    public VendorContactHistoryRecord value1(String value) {
        setVendorCode(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord value2(String value) {
        setSerialNo(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord value3(String value) {
        setFlagType(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord value4(String value) {
        setContactPersonName(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord value5(String value) {
        setDesignation(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord value6(String value) {
        setDepartment(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord value7(String value) {
        setTelephoneNo(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord value8(String value) {
        setMobileNo(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord value9(String value) {
        setEmailId(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord value10(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord value11(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord value12(String value) {
        setLastChangedBy(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord value13(LocalDateTime value) {
        setLastChangedOn(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord value14(String value) {
        setContactDeclarationName(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord value15(String value) {
        setContactDeclarationNo(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord value16(LocalDateTime value) {
        setLastEditedOn(value);
        return this;
    }

    @Override
    public VendorContactHistoryRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, LocalDateTime value11, String value12, LocalDateTime value13, String value14, String value15, LocalDateTime value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VendorContactHistoryRecord
     */
    public VendorContactHistoryRecord() {
        super(VendorContactHistory.VENDOR_CONTACT_HISTORY);
    }

    /**
     * Create a detached, initialised VendorContactHistoryRecord
     */
    public VendorContactHistoryRecord(String vendorCode, String serialNo, String flagType, String contactPersonName, String designation, String department, String telephoneNo, String mobileNo, String emailId, String createdBy, LocalDateTime createdOn, String lastChangedBy, LocalDateTime lastChangedOn, String contactDeclarationName, String contactDeclarationNo, LocalDateTime lastEditedOn) {
        super(VendorContactHistory.VENDOR_CONTACT_HISTORY);

        setVendorCode(vendorCode);
        setSerialNo(serialNo);
        setFlagType(flagType);
        setContactPersonName(contactPersonName);
        setDesignation(designation);
        setDepartment(department);
        setTelephoneNo(telephoneNo);
        setMobileNo(mobileNo);
        setEmailId(emailId);
        setCreatedBy(createdBy);
        setCreatedOn(createdOn);
        setLastChangedBy(lastChangedBy);
        setLastChangedOn(lastChangedOn);
        setContactDeclarationName(contactDeclarationName);
        setContactDeclarationNo(contactDeclarationNo);
        setLastEditedOn(lastEditedOn);
    }
}
