/*
 * This file is generated by jOOQ.
 */
package com.jooq.jooq.model.tables.records;


import com.jooq.jooq.model.tables.VendorVehicleDetails;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VendorVehicleDetailsRecord extends UpdatableRecordImpl<VendorVehicleDetailsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.COMP_CODE</code>.
     */
    public VendorVehicleDetailsRecord setCompCode(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.COMP_CODE</code>.
     */
    public String getCompCode() {
        return (String) get(0);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.SERVICE_AGENT</code>.
     */
    public VendorVehicleDetailsRecord setServiceAgent(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.SERVICE_AGENT</code>.
     */
    public String getServiceAgent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.PAYMENT_VENDOR</code>.
     */
    public VendorVehicleDetailsRecord setPaymentVendor(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.PAYMENT_VENDOR</code>.
     */
    public String getPaymentVendor() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.TRUCK_NUMBER</code>.
     */
    public VendorVehicleDetailsRecord setTruckNumber(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.TRUCK_NUMBER</code>.
     */
    public String getTruckNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.NAME1</code>.
     */
    public VendorVehicleDetailsRecord setName1(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.NAME1</code>.
     */
    public String getName1() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.PAYEE_VENDOR_NAME</code>.
     */
    public VendorVehicleDetailsRecord setPayeeVendorName(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.PAYEE_VENDOR_NAME</code>.
     */
    public String getPayeeVendorName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.PERMIT_STATUS</code>.
     */
    public VendorVehicleDetailsRecord setPermitStatus(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.PERMIT_STATUS</code>.
     */
    public String getPermitStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.BIRTH_DATE</code>.
     */
    public VendorVehicleDetailsRecord setBirthDate(LocalDate value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.BIRTH_DATE</code>.
     */
    public LocalDate getBirthDate() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.DIESEL_CARD_NUMBER</code>.
     */
    public VendorVehicleDetailsRecord setDieselCardNumber(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.DIESEL_CARD_NUMBER</code>.
     */
    public String getDieselCardNumber() {
        return (String) get(8);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.TRUCK_TYPE</code>.
     */
    public VendorVehicleDetailsRecord setTruckType(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.TRUCK_TYPE</code>.
     */
    public String getTruckType() {
        return (String) get(9);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.VEHICLE_TYPE</code>.
     */
    public VendorVehicleDetailsRecord setVehicleType(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.VEHICLE_TYPE</code>.
     */
    public String getVehicleType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.CRATE_CAPACITY</code>.
     */
    public VendorVehicleDetailsRecord setCrateCapacity(BigDecimal value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.CRATE_CAPACITY</code>.
     */
    public BigDecimal getCrateCapacity() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.STATUS</code>.
     */
    public VendorVehicleDetailsRecord setStatus(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(12);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.CREATED_BY</code>.
     */
    public VendorVehicleDetailsRecord setCreatedBy(Integer value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.CREATED_BY</code>.
     */
    public Integer getCreatedBy() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.CREATED_ON</code>.
     */
    public VendorVehicleDetailsRecord setCreatedOn(LocalDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.CREATED_ON</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.LAST_CHANGED_BY</code>.
     */
    public VendorVehicleDetailsRecord setLastChangedBy(Integer value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.LAST_CHANGED_BY</code>.
     */
    public Integer getLastChangedBy() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.LAST_CHANGED_ON</code>.
     */
    public VendorVehicleDetailsRecord setLastChangedOn(LocalDateTime value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.LAST_CHANGED_ON</code>.
     */
    public LocalDateTime getLastChangedOn() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.SUPPL1_DES</code>.
     */
    public VendorVehicleDetailsRecord setSuppl1Des(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.SUPPL1_DES</code>.
     */
    public String getSuppl1Des() {
        return (String) get(17);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.SUPPL2_DES</code>.
     */
    public VendorVehicleDetailsRecord setSuppl2Des(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.SUPPL2_DES</code>.
     */
    public String getSuppl2Des() {
        return (String) get(18);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.SUPPL3_DES</code>.
     */
    public VendorVehicleDetailsRecord setSuppl3Des(String value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.SUPPL3_DES</code>.
     */
    public String getSuppl3Des() {
        return (String) get(19);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.SUPPL4_DES</code>.
     */
    public VendorVehicleDetailsRecord setSuppl4Des(String value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.SUPPL4_DES</code>.
     */
    public String getSuppl4Des() {
        return (String) get(20);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.DELETION</code>.
     */
    public VendorVehicleDetailsRecord setDeletion(String value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.DELETION</code>.
     */
    public String getDeletion() {
        return (String) get(21);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.FSSAI_FROM_DATE</code>.
     */
    public VendorVehicleDetailsRecord setFssaiFromDate(LocalDate value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.FSSAI_FROM_DATE</code>.
     */
    public LocalDate getFssaiFromDate() {
        return (LocalDate) get(22);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.FSSAI_TO_DATE</code>.
     */
    public VendorVehicleDetailsRecord setFssaiToDate(LocalDate value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.FSSAI_TO_DATE</code>.
     */
    public LocalDate getFssaiToDate() {
        return (LocalDate) get(23);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.CFA_NAME</code>.
     */
    public VendorVehicleDetailsRecord setCfaName(String value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.CFA_NAME</code>.
     */
    public String getCfaName() {
        return (String) get(24);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.CFA_REF</code>.
     */
    public VendorVehicleDetailsRecord setCfaRef(String value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.CFA_REF</code>.
     */
    public String getCfaRef() {
        return (String) get(25);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.ZEMISSION_CEF</code>.
     */
    public VendorVehicleDetailsRecord setZemissionCef(String value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.ZEMISSION_CEF</code>.
     */
    public String getZemissionCef() {
        return (String) get(26);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.ZEMIS_FDATE</code>.
     */
    public VendorVehicleDetailsRecord setZemisFdate(LocalDate value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.ZEMIS_FDATE</code>.
     */
    public LocalDate getZemisFdate() {
        return (LocalDate) get(27);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.ZEMIS_TDATE</code>.
     */
    public VendorVehicleDetailsRecord setZemisTdate(LocalDate value) {
        set(28, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.ZEMIS_TDATE</code>.
     */
    public LocalDate getZemisTdate() {
        return (LocalDate) get(28);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.ZFCOMP_QTY</code>.
     */
    public VendorVehicleDetailsRecord setZfcompQty(BigDecimal value) {
        set(29, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.ZFCOMP_QTY</code>.
     */
    public BigDecimal getZfcompQty() {
        return (BigDecimal) get(29);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.ZMCOMP_QTY</code>.
     */
    public VendorVehicleDetailsRecord setZmcompQty(BigDecimal value) {
        set(30, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.ZMCOMP_QTY</code>.
     */
    public BigDecimal getZmcompQty() {
        return (BigDecimal) get(30);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.ZBCOMP_QTY</code>.
     */
    public VendorVehicleDetailsRecord setZbcompQty(BigDecimal value) {
        set(31, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.ZBCOMP_QTY</code>.
     */
    public BigDecimal getZbcompQty() {
        return (BigDecimal) get(31);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.ZVEH_FC_NO</code>.
     */
    public VendorVehicleDetailsRecord setZvehFcNo(String value) {
        set(32, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.ZVEH_FC_NO</code>.
     */
    public String getZvehFcNo() {
        return (String) get(32);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.ZVEH_FC_FDATE</code>.
     */
    public VendorVehicleDetailsRecord setZvehFcFdate(LocalDate value) {
        set(33, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.ZVEH_FC_FDATE</code>.
     */
    public LocalDate getZvehFcFdate() {
        return (LocalDate) get(33);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.ZVEH_FC_TDATE</code>.
     */
    public VendorVehicleDetailsRecord setZvehFcTdate(LocalDate value) {
        set(34, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.ZVEH_FC_TDATE</code>.
     */
    public LocalDate getZvehFcTdate() {
        return (LocalDate) get(34);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.ZVEH_INSUR_NO</code>.
     */
    public VendorVehicleDetailsRecord setZvehInsurNo(String value) {
        set(35, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.ZVEH_INSUR_NO</code>.
     */
    public String getZvehInsurNo() {
        return (String) get(35);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.ZVEH_INS_FDATE</code>.
     */
    public VendorVehicleDetailsRecord setZvehInsFdate(LocalDate value) {
        set(36, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.ZVEH_INS_FDATE</code>.
     */
    public LocalDate getZvehInsFdate() {
        return (LocalDate) get(36);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.ZVEH_INS_TDATE</code>.
     */
    public VendorVehicleDetailsRecord setZvehInsTdate(LocalDate value) {
        set(37, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.ZVEH_INS_TDATE</code>.
     */
    public LocalDate getZvehInsTdate() {
        return (LocalDate) get(37);
    }

    /**
     * Setter for <code>vendor_portal_pbx.vendor_vehicle_details.ZFSSAI_NO</code>.
     */
    public VendorVehicleDetailsRecord setZfssaiNo(String value) {
        set(38, value);
        return this;
    }

    /**
     * Getter for <code>vendor_portal_pbx.vendor_vehicle_details.ZFSSAI_NO</code>.
     */
    public String getZfssaiNo() {
        return (String) get(38);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VendorVehicleDetailsRecord
     */
    public VendorVehicleDetailsRecord() {
        super(VendorVehicleDetails.VENDOR_VEHICLE_DETAILS);
    }

    /**
     * Create a detached, initialised VendorVehicleDetailsRecord
     */
    public VendorVehicleDetailsRecord(String compCode, String serviceAgent, String paymentVendor, String truckNumber, String name1, String payeeVendorName, String permitStatus, LocalDate birthDate, String dieselCardNumber, String truckType, String vehicleType, BigDecimal crateCapacity, String status, Integer createdBy, LocalDateTime createdOn, Integer lastChangedBy, LocalDateTime lastChangedOn, String suppl1Des, String suppl2Des, String suppl3Des, String suppl4Des, String deletion, LocalDate fssaiFromDate, LocalDate fssaiToDate, String cfaName, String cfaRef, String zemissionCef, LocalDate zemisFdate, LocalDate zemisTdate, BigDecimal zfcompQty, BigDecimal zmcompQty, BigDecimal zbcompQty, String zvehFcNo, LocalDate zvehFcFdate, LocalDate zvehFcTdate, String zvehInsurNo, LocalDate zvehInsFdate, LocalDate zvehInsTdate, String zfssaiNo) {
        super(VendorVehicleDetails.VENDOR_VEHICLE_DETAILS);

        setCompCode(compCode);
        setServiceAgent(serviceAgent);
        setPaymentVendor(paymentVendor);
        setTruckNumber(truckNumber);
        setName1(name1);
        setPayeeVendorName(payeeVendorName);
        setPermitStatus(permitStatus);
        setBirthDate(birthDate);
        setDieselCardNumber(dieselCardNumber);
        setTruckType(truckType);
        setVehicleType(vehicleType);
        setCrateCapacity(crateCapacity);
        setStatus(status);
        setCreatedBy(createdBy);
        setCreatedOn(createdOn);
        setLastChangedBy(lastChangedBy);
        setLastChangedOn(lastChangedOn);
        setSuppl1Des(suppl1Des);
        setSuppl2Des(suppl2Des);
        setSuppl3Des(suppl3Des);
        setSuppl4Des(suppl4Des);
        setDeletion(deletion);
        setFssaiFromDate(fssaiFromDate);
        setFssaiToDate(fssaiToDate);
        setCfaName(cfaName);
        setCfaRef(cfaRef);
        setZemissionCef(zemissionCef);
        setZemisFdate(zemisFdate);
        setZemisTdate(zemisTdate);
        setZfcompQty(zfcompQty);
        setZmcompQty(zmcompQty);
        setZbcompQty(zbcompQty);
        setZvehFcNo(zvehFcNo);
        setZvehFcFdate(zvehFcFdate);
        setZvehFcTdate(zvehFcTdate);
        setZvehInsurNo(zvehInsurNo);
        setZvehInsFdate(zvehInsFdate);
        setZvehInsTdate(zvehInsTdate);
        setZfssaiNo(zfssaiNo);
    }
}
